### ISSUE TITLE
postRegistrationHandler invoked only if register.autoAuthorize is set to true

### ISSUE THREAD

**Issue by agonbina** [stormpath/express-stormpath#114]
This isn't mentioned in the docs, but after looking at this piece of code here: https://github.com/stormpath/stormpath-express/blob/a844b24ca90acf2db052e36d8ef92706ac269e71/lib/controllers/register.js#L119 I noticed that postRegistrationHandler is invoked only when ```web.register.autoAuthorize``` is set to true.

I don't think we want to autoAuthorize the user in every situation, if by autoAuthorize we mean the user will be automatically logged in after they have registered?

**Comment by robertjd** [comment]
This is a bug, we should call the post registration handler even if the `autoAuthorize` option is false.  I'm working on this now.

**Comment by robertjd** [comment]
This should be fixed in the new 2.0.10 release.
