### ISSUE TITLE
acesss and refresh tokens can be reused after logout

### ISSUE THREAD

**Issue by stevebread** [stormpath/express-stormpath#127]
I am using express-stormpath with the angular-sdk. On logout, express-stormpath clears the access and refesh tokens from the cookie. If the old token values are manually applied e.g. via the browser console, it is then possible to perform any request that requires authentication without needing to re-login.

**Comment by stevebread** [comment]
Looked into JWT tokens and it seems this is how they work in the absence of an explicit revocation list

**Comment by robertjd** [comment]
In theory yes, in practice: Stormpath does maintain that revocation list for you :)

This integration should be deleting the tokens on logout, I'm flagging this to go in a release as a fix.

For me information about Stormpath's token management features, please see:

http://docs.stormpath.com/guides/token-management/
