### ISSUE TITLE
Discuss: use of `stormpath` keyword

### ISSUE THREAD

**Issue by robertjd** [stormpath/express-stormpath#128]
Our examples say that you shoud import this module like this:

```javascript
var stormpath = require('express-stormpath');
```

This is proving confusing, because our node docs also do the same thing:

```javascript
var stormpath = require('stormpath');
```

Alas, it's unclear which API you're actually working with - the framework integration, or the SDK.

I believe that our examples should use this form:

```javascript
var expressStormpath = require('express-stormpath');
```

**Comment by typerandom** [comment]
+1 for being explicit with `expressStormpath`.

**Comment by rdegges** [comment]
I totally disagree. Users using this library will likely only have this be their 'stormpath' experience. Namespacing this differently doesn't make sense, IMO, as it makes your middleware codez look ugly.

```javascript
app.get('/', stormpath.loginRequired, ...);

// vs

app.get('/', expressStormpath.loginRequired, ...);
```

The current stuff looks pretty elegant this way, imo.

**Comment by typerandom** [comment]
I agree with it looking better, but isn't also many using the SDK in the integrations? But if there is no (or little) chance that they're going to be working with the SDK then I'd agree that just `stormpath` is nicer.

**Comment by robertjd** [comment]
Most people start with `express-stormpath`, then move on to needing more advanced features that require the underlying SDK.  Some people are happy to pull the constructed client out of the integration state (aka `req.app.get('stormpthClient')` and use that to get work done, but others end up installing the SDK as a top-level library.  It gets confusing when helping people debug.

I'm really resistant to the "looks better" argument when the underlying API's are totally different.

**Comment by rdegges** [comment]
If people are using express-stormpath, and want to access the underlying client, we should tell them how to do that in the docs.

They have two choices:

```javascript
app.get('stormpathClient')

// or, inside of a route:
req.app.get('stormpathClient')
```

They should never ever import the stormpath library directly, as it'll create a duplicate client which causes 2x caching / all the issues we've had originally.

**Comment by robertjd** [comment]
I agree that a creating two clients is problematic, if you're not aware of the caching issues.  I still feel dirty every time I call this export `stormpath`, but I do see how it makes things feel simpler.  Closing.
