### ISSUE TITLE
Misleading infos into the "API Authentication: Basic Auth" section of the doc

### ISSUE THREAD

**Issue by pierredavidbelanger** [stormpath/express-stormpath#130]
Here
https://docs.stormpath.com/nodejs/express/latest/authentication.html#api-authentication-basic-auth

Where it says:

> In order for your API clients to authenticate with this endpoing, they need to supply an HTTP Authorization header, like this:
> `Authentication: Bearer <Base64UrlSafe(apiKeyId:apiKeySecret)>`

It should be `Authorization` instead of `Authentication`, and `Basic` instead of `Bearer` (this is indeed what one will get using `curl`):

`Authorization: Basic <Base64UrlSafe(apiKeyId:apiKeySecret)>`

**Comment by robertjd** [comment]
Thanks @pierredavidbelanger !

This was resolved in 2.2.0, which had a major re-write of the authentication section of the documentation.
