### ISSUE TITLE
Delete cookies doesn't accept parameters

### ISSUE THREAD

**Issue by suryod** [stormpath/express-stormpath#155]
Hi,

When creating accessToken cookie (lib/helpers/create-session.js), it supplies the `accessTokenCookie` parameters. But when deleting accessToken cookie (lib/middleware/delete-cookies.js) it doesn't supplies the parameters. Can you make it so it'll accept the parameters as well. I'm having problem when `accessTokenCookie` is set, users can login but unable to logout because the cookie's domain is not matching.

Thank you,
Indra

**Comment by typerandom** [comment]
Hi Indra.

Thanks for reporting this. We'll be looking into this issue soon. I know that this was reported some time ago, but please, if this still is an issue and is hindering you in your work, please let us know.

Cheers!

**Comment by harai** [comment]
I have exactly the same problem now.
