### ISSUE TITLE
Stale account data after `req.user.save()`

### ISSUE THREAD

**Issue by robertjd** [stormpath/express-stormpath#156]
To reproduce, create a post-registration handler.  Also enable the `autoLogin: true ` option (and ensure that your directory has email verification turned off).  In that handler, modify the account's custom data like so:

```
req.user.customData.thing = " a value";
req.user.save(next);
```

On the next request to the server, notice that the custom data `thing` value is not present on the `req.user.customData` object

However if you save the custom data object, the property will be available on the next request:

```
req.user.customData.save(next);
```

**Comment by typerandom** [comment]
Important to note: One also have to specify `expand: { customData: true }` in config in order to access the custom data through the `account.customData` property in the next request. Optionally, without expand one can also call `account.getCustomData()`.
