### ISSUE TITLE
Implement password grant & refresh grant flow for oauth endpoint

### ISSUE THREAD

**Issue by robertjd** [stormpath/express-stormpath#162]
This library needs to support `grant_type=password` on the `/oauth/token` endpoint.  The implementation of this handler will look very similar to this:

https://github.com/stormpath/express-stormpath/blob/master/lib/controllers/login.js#L53-L56

But rather than settings cookies we need to respond with the OAuth-specificed response body, which is a JSON object that looks like this:

```
{
  "access_token": "eyJraWQ...",
  "expires_in": 1800
  "refresh_token": "eyJraWQiOiI...Y",
  "token_type": "Bearer",
}
```

As such we also need to implement the `refresh_token` grant flow, allowing the user to exchange their refresh token for an access token

The `apiAuthenticationRequired` middleware will also need to be modified to accept these access tokens via `Authorization: Bearer <access_token>`

**Comment by wimolivier** [comment]
Thanks Robert, it will be great to have this working.

**Comment by robertjd** [comment]
Hello @wimolivier , this is now in release 2.2.0 :)

**Comment by wimolivier** [comment]
Thanks a mil!
