### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by rdegges** [stormpath/express-stormpath#166]
http://docs.stormpath.com/nodejs/express/latest/templates.html

<img width="323" alt="screenshot 2015-10-26 10 21 58" src="https://cloud.githubusercontent.com/assets/90247/10736646/6b1aa9de-7bcb-11e5-8714-eccdebef1336.png">

We shouldn't make typos in the docs! Let's get everything on this page fixed <3

**Comment by JrodManU** [comment]
I submitted a pull request to fix many typos.

**Comment by rdegges** [comment]
Just merged it in, thanks soooo much <33
