### ISSUE TITLE
email authentication wiping out customData created by postRegistrationHandler

### ISSUE THREAD

**Issue by adamdiy** [stormpath/express-stormpath#177]
hello,

i have a simple web app using express-stormpath. when users register with no email verification, everything works as expected: postRegistrationHandler fires, and i initialize several variables in customData.

when people register with email verification, postRegistrationHandler fires and initializes their customData with desired values. however, when they verify their email, their customData is wiped clean and i lose the initialized values.

is this the intended behavior? just because i don't see anything about this in  https://docs.stormpath.com/nodejs/express/latest/registration.html#email-verification

any other way to initialize these values once? using a postLoginHandler to do something once seems hacky....

thanks
a

**Comment by adamdiy** [comment]
nm! think i had postRegHandler set up wrong and it wasn't always working correctly / sometimes exiting before initialization was complete

**Comment by robertjd** [comment]
Hi @adamdiy, thanks for the follow up!  Do you remember what the problem was?
