### ISSUE TITLE
Configuration fails if appliction is not defined, but only one application exists

### ISSUE THREAD

**Issue by robertjd** [stormpath/express-stormpath#181]
We want to support this scenario: you have not defined an application href for configuration, but your tenant only has one application - mostly likely the default "My Application" that was created for you when you created your tenant.  In this scenario we should automatically use that application, if you have not explicitly defined a application by name or href.

However, if you have not explicitly defined an application and you have more than one application your tenant, then you should receive an error which tells you that you need to define an application.

Note: there is an application that every tenant has, named "Stormpath Administrators".  This application should be ignored when considering the total count of applications in the tenant.

**Comment by typerandom** [comment]
One question, is the Stormpath application really named 'Stormpath Administrators' and not just 'Stormpath'?

**Comment by lhazlewood** [comment]
The application is named Stormpath.  The directory it is mapped to is Stormpath Administrators.

**Comment by typerandom** [comment]
@lhazlewood Thanks!
