### ISSUE TITLE
Login Not Working

### ISSUE THREAD

**Issue by rdegges** [stormpath/express-stormpath#184]
In the latest release, logging in via the default login route is NOT working. The page gets reloaded and sits still...

**Comment by rdegges** [comment]
Here's a GIF showing what I mean: http://g.recordit.co/JpVMeH3aZW.gif

**Comment by typerandom** [comment]
I'm unable to reproduce this. This is how it looks for me:

![stormpath-express 2.1.0 login](http://g.recordit.co/OptdHNPrwl.gif])

Do you see any client-side/request errors or things like that?

**Comment by robertjd** [comment]
I cannot reproduce with our sample project, @rdegges can you try this: https://github.com/stormpath/express-stormpath-sample-project

**Comment by robertjd** [comment]
bump @rdegges - are you still able to reproduce this problem?

**Comment by rdegges** [comment]
This is now working -- I'm able to get it going. I wonder if maybe some odd network stuff was going on :(
