### ISSUE TITLE
"Error: API key ID and secret is required" even though my process.env vars are set correctly

### ISSUE THREAD

**Issue by icd2k3** [stormpath/express-stormpath#187]
Hey guys,

I'm having a bit of trouble getting this all set up. It looks like my process.env vars are set correctly, but whenever I try to init express-stormpath I get:

    error:  Error: API key ID and secret is required.
    at newError ([....]/node_modules/stormpath-config/lib/strategy/ValidateClientConfigStrategy.js:15:14)
    at ValidateClientConfigStrategy.process ([....]/node_modules/stormpath-config/lib/strategy/ValidateClientConfigStrategy.js:33:12)
    at fn [....]/node_modules/async/lib/async.js:741:34)
    at [....]/node_modules/async/lib/async.js:1208:16
    at [....]/node_modules/async/lib/async.js:166:37
    at [....]/node_modules/async/lib/async.js:701:43
    at [....]/node_modules/async/lib/async.js:167:37
    at Immediate._onImmediate ([....]/node_modules/async/lib/async.js:1201:34)
    at processImmediate [as _immediateCallback] (timers.js:368:17)

It looks like I have these set correctly (according to the current [documentation](https://docs.stormpath.com/nodejs/express/latest/configuration.html#environment-variables)) because when I run `printenv` I see the expected data in the output:

    STORMPATH_CLIENT_APIKEY_ID=xxxx
    STORMPATH_CLIENT_APIKEY_SECRET=xxxx
    STORMPATH_APPLICATION_HREF=xxxx

My code is the same as documentation:

    var express = require('express');
    var app = express();
    var stormpath = require('express-stormpath');
    app.use(stormpath.init(app, {
        api: true
    }));

Info:
- environment: local
- heroku app
- express-stormpath 2.1.0

Any ideas of things I could try to get this up and running? Thanks!

**Comment by icd2k3** [comment]
Ok I figured this out - hopefully this will help anyone experiencing a similar issue when trying to get express-stormpath running locally:

I use [gulp-live-server](https://github.com/gimm/gulp-live-server) as my local dev server. With this plugin you have to pass node env variables explicitly as options like so:

    var server = gls('app.js', {
        env: {
            STORMPATH_CLIENT_APIKEY_ID: process.env.STORMPATH_CLIENT_APIKEY_ID,
            STORMPATH_CLIENT_APIKEY_SECRET: process.env.STORMPATH_CLIENT_APIKEY_SECRET,
            STORMPATH_APPLICATION_HREF: process.env.STORMPATH_APPLICATION_HREF
        }
    });

**Comment by robertjd** [comment]
Thanks for the follow up!
