### ISSUE TITLE
Problem with SPA & /login

### ISSUE THREAD

**Issue by icd2k3** [stormpath/express-stormpath#188]
Hey guys,

I have a single page React application. I'm able to call /register via AJAX and create accounts without issue, but when I try to use /login the response is a 302 redirect to '/' and I get no response data for the /login call.

My config looks like:
    
    app.use(stormpath.init(app, {
        app: true,
        web: {
            spaRoot: path.join(__dirname, 'src', 'index.html'),
            login: {
                enabled : true,
                uri     : '/login'
            },
            register: {
                enabled : true,
                uri     : '/register'
            }
        },
        postRegistrationHandler: function(account, req, res, next) {
            console.log('User: ' + account.email + ' just registered!');
            next();
        },
        postLoginHandler: function(account, req, res, next) {
            console.log('User: ' + account.email + ' just logged in!');
            next();
        }
    }));

postLoginHandler is never called - here's a video of the request: http://cl.ly/2Z2I0u1I3Y0e

Any ideas on what I can do here? Maybe a way to not redirect after the login call? As I mentioned registration works great and returns the data I expect, but login is not.

Thanks for any advice.

Info:
- express-stormpath 2.1.0

**Comment by robertjd** [comment]
Can you look at the value of the `Accept` header that your React application is sending in it's requests?  It should be `application/json` if you want to use the JSON responses from this library.  Otherwise you'll be getting the HTML responses and redirects.

Thanks!

**Comment by icd2k3** [comment]
hey @robertjd thanks for the quick response! yep I'm setting those headers:

    xmlHttp.setRequestHeader('Content-type', 'application/json;charset=UTF-8');
    xmlHttp.setRequestHeader('Accept', 'application/json');

When I call /register they show up correctly too:

Request Headers:
    Accept:application/json
    Content-type:application/json;charset=UTF-8

**Comment by icd2k3** [comment]
Update:

I was able to modify my code to just use the generic node api client (see below) - but it looks like default `/login` functionality for express-stormpath is still an issue. Here is my modified code that works:

    app.use(stormpath.init(app, {
        app: true,
        web: {
            spaRoot: path.join(__dirname, 'src', 'index.html'),
            login: {
                enabled : false
            },
            register: {
                enabled: true,
                uri: '/register'
            }
        },
        postRegistrationHandler: function(account, req, res, next) {
            log('User: ' + account.email + ' just registered!');
            next();
        }
    }));

    app.on('stormpath.ready', function(){
        stormpathClient = app.get('stormpathClient');
        stormpathClient.getApplications(function(err, applications) {
            if(err) { console.log(err); }
            applications.each(function(application, cb) {
                stormpathApp = application;
                cb();
            });
        });
        http.listen(process.env.PORT || 80, function(){
            log('listening on *:80');
        });
    });

    app.post('/login', function(req, res) {
        stormpathApp.authenticateAccount(req.body, function(err, authResponse) {
            if(err) { console.log(err); res.json(err); }
            authResponse.getAccount(function(err, account) {
                if(err) { console.log(err); res.json(err); }
                res.json(account);
            });
        });
    });

Note that I'm just completely disabling express-stormpath's built in functionality and relying on the generic node [api](http://docs.stormpath.com/nodejs/api/home)

**Comment by robertjd** [comment]
Hi @icd2k3 , thank you for the follow up.  It looks like you wanted to modify our login response to return the user object or error (instead of redirecting to the nextUri) because it wasn't doing that by default.  Is that correct?    Just checking so that I know where I should start investigating again.

**Comment by icd2k3** [comment]
Hey @robertjd, thanks for the reply. Yep that is correct. In my SPA `/register` returns a json object as expected, but `/login` looks like it attempts a redirect (even with json headers).

**Comment by typerandom** [comment]
I'm closing this issue since it looks like it is resolved.

@icd2k3 We now have a [React SDK](https://github.com/stormpath/stormpath-sdk-react). So if you are interested, take a look at https://github.com/stormpath/stormpath-sdk-react and if you still experience the same issue there, then open a new issue there and let me know.

Cheers! :)

**Comment by icd2k3** [comment]
Thanks @typerandom I'll switch over to that, cheers!

**Comment by bentedder** [comment]
I am having the same issue w/the /login route. Am attempting your fix of going straight to stormpath with no luck. Will do a bit more digging.
