### ISSUE TITLE
React Isomorphic - /me not unauthorized on server side.

### ISSUE THREAD

**Issue by guzmo** [stormpath/express-stormpath#199]
Hey,

Im building an isomorphic React app.
The problem is rendering on server side ( which means I will call /me to get the user and see if he/she is authorized ) I always get unauthorized. The access_token is passed to the server on user request but when the server tries to call /me it wont work. The access_token isnt there anymore.

I'm using fetch to do the ajax requests and I do use:

headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json'
},
credentials: 'same-origin'

Any ideas?

**Comment by robertjd** [comment]
Hi @guzmo , thank you for the information.  Could you tell us more information about the React libraries you are using?  We're just now starting to look into React.  Here are a few things you can try, that I know have worked for others:

In the React code:
```
credentials: 'include'
```

In our express-stormpath configuration:

``` 
app.use(stormpath.init(app,{
  web: {
    accessTokenCookie: {
      domain: '.localhost'
    },
    refreshTokenCookie: {
      domain: '.localhost'
    }
  }
}));
``` 

I hope this helps!  Please let us know if not.  Ping @typerandom as he is looking at React + Stormpath as well.

**Comment by guzmo** [comment]
Thanks for the quick response.

I'm using the project template from https://github.com/DominicTobias/universal-react.

It uses a static method call to requestState() in the Component to load the data at startup, and on the client side it checks whether the data already is there, use it, otherwise load the data.

For ex:
```
static requestState() {
     return UserStore.checkLogin();
};

constructor(props, context) {
  if (!context.getInitialData(this)) {
	App.requestState().then(user => {
	    this.setState({
		user: user,
		loaded: true
	    });
	});
  }
  this.state = {
      user: context.getInitialData(this),
      loaded: true
  };
}
```

My call to /me in the UserStore.checkLogin():
```
return fetch('http://localhost:3000/me, {
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json'
      },
      credentials: 'include'
      //credentials: 'same-origin'
});
```

Some of the current libraries I used atm:
```
"es6-promise": "^3.0.2",
"express": "^4.13.3",
"express-stormpath": "^2.2.0",
"isomorphic-fetch": "^2.2.0",
"jquery": "^2.1.4",
"mongoose": "^4.2.5",
"react": "^0.14.1",
"react-bootstrap": "^0.27.3",
"react-bootstrap-validation": "^0.1.8",
"react-dom": "^0.14.1",
"react-helmet": "^2.1.1",
"react-loader": "^2.0.0",
"react-router": "^1.0.0",
"react-router-bootstrap": "0.19.3",
```

I'll try to find some time and ping @typerandom later today maybe :)

**Comment by typerandom** [comment]
Hey,

@guzmo I'm closing since it's unrelated to the Express integration. If this problem still persists, then please open a new issue in our React SDK repository:

https://github.com/stormpath/stormpath-sdk-react

Cheers! :)
