### ISSUE TITLE
req.stormpathSession not defined in 2.2.0

### ISSUE THREAD

**Issue by ppitonak** [stormpath/express-stormpath#202]
In Stormpath 1.x, req.stormpathSession was defined but it's undefined in 2.x. It is either a bug or it should be documented properly.

**Comment by ppitonak** [comment]
Still present in 2.3.3

**Comment by robertjd** [comment]
Hello Pavol!  Thank you for pointing this out.  The property `req.stormpathSession` has been removed, if you were using this property to store stateful session information you will need to add a session middleware to your library, such as [express-session](https://github.com/expressjs/session), and use that module instead.

I'm amending the upgrade log to discuss this, please see #236 

Thanks again!
