### ISSUE TITLE
register.autoAuthorize not Respected

### ISSUE THREAD

**Issue by rdegges** [stormpath/express-stormpath#205]
I'm trying to enable the autoAuthorize functionality, so that after a user has registered a new account, they'll be automatically logged in.

This should be enabled when the config is set such that:

```javascript
{
  web: {
    register: {
      autoAuthorize: true
    }
  },
  website: true
}
```

But this is not working. Once I create an account, I'm still greeted by the following page (bad):

<img width="1274" alt="screenshot 2015-11-16 16 56 14" src="https://cloud.githubusercontent.com/assets/90247/11199530/2a520d16-8c83-11e5-8272-7b155139817b.png">

We should instead be generating the access / refresh tokens, storing them in cookies, and sending the user to the nextUrl. This is a regression.

**Comment by robertjd** [comment]
The property is `register.autoLogin`, we had some incorrect documentation at one point in the past.  This is fixed now.
