### ISSUE TITLE
Fix Client Credentials

### ISSUE THREAD

**Issue by rdegges** [stormpath/express-stormpath#224]
Right now, you can't specify the grant type in the querystring params for the POST to /oauth/token, eg:

```console
$ curl -X POST http://localhost:3000/oauth/token?grant_type=client_credentials
```

The above should work. Right now this only works if you put the grant type in the body, eg:

```console
$ curl -X POST --data 'grant_type=client_credentials' http://localhost:3000/oauth/token
```

**Comment by rdegges** [comment]
We should also get some tests for this when we patch to assert we don't break this in the future -- this was previously working.

**Comment by robertjd** [comment]
The OAuth2 spec requires this in the request body, we will not support this is a query parameter.

The method `application.authenticateApiRequest` in the Node SDK *does* look for this as a query parameter, but that is wrong and needs to be removed.
