### ISSUE TITLE
Access and refresh token cookies are not secure when using https

### ISSUE THREAD

**Issue by stevebread** [stormpath/express-stormpath#228]
create-session.js checks if the request is https to decide whether to make the cookie secure only if
`refreshTokenCookieConfig.https !== null`. However, the property in config.yml is named `secure` and not `https` so this condition returns true since `https` is undefined and the request protocol is not checked.

**Comment by robertjd** [comment]
Thanks @stevebread for reporting this!  We just fixed this in a new release, 2.3.3 - and I've added you to the [contributors doc](https://github.com/stormpath/express-stormpath/blob/master/docs/contributors.rst).  Have a great weekend!

**Comment by stevebread** [comment]
Thanks for the fix and the mention Robert!
