### ISSUE TITLE
Express version reporting is incorrect

### ISSUE THREAD

**Issue by robertjd** [stormpath/express-stormpath#239]
We're adding an express version to our user agent string, here:

https://github.com/stormpath/express-stormpath/blob/master/lib/stormpath.js#L26

However, that is going to require the version of express that is depended on by this library in package.json (not the version of express that the developer is using). The UA string is not telling us what version of express was used to create the app that was passed into our init() function.

As such, unless we can find a way to know what version of express has been used to create the app (I don't know how?), I think we should remove this from the UA because it's useless.  We should also move express to `devDependencies`, as there is no reason to have this as a prod dependency (we only use express directly in our tests).

Ping @typerandom @rdegges

**Comment by rdegges** [comment]
Agreed -- I didn't realize this was how it worked. I *thought* the way require worked is that it'd cache things as soon as it's loaded, in which case it is likely the user's code would be loaded first, and their version of express as well?

I just made a test app though, and you're 100% correct.

I say we move it to devDependencies, and get rid of it in the UA string. Sorta a bummer though. Wish we had that information =)

**Comment by typerandom** [comment]
I might have a solution. What if we just got the process path, then resolved the module from its node_modules folder? Then if that doesn't exist, resolve it from the global node_modules path?

I have made a PR that does this, so if you'd like to check that out, that would be awesome.
