### ISSUE TITLE
Issue access+refresh token after social login

### ISSUE THREAD

**Issue by rdegges** [stormpath/express-stormpath#247]
Right now, we have a blocker for our iOS contractor, and anyone implementing mobile SDKs.

Let's say you're attempting to build Facebook login support into iOS. The flow you'd want to take is as follows:

- Create a Stormpath Application with a mapped Facebook Directory.
- Create an express-stormpath sample app that has the login functionality enabled.
- Use the Facebook OAuth2 API to authenticate a user via the OAuth2 flow and obtain an access token.
- POST this access token to the /login endpoint that express-stormpath provides. This might look like so:

```console
$ curl -vX POST \
    -H "Accept: application/json"
    -H "Content-Type: application/json"
    --data '{"providerData": {"providerId": "facebook", "accessToken": "CAADMXRqlX9gBAAgNM6F15uKBzAmbwj4ZCJhyvSb00OVrgZAW1fIACh8ebDtZCUfCTcrpVUP8krkyJob3muZBPderd3uAX2Mz2a4V71T2pIvy44fDxG35hXDjtSZCCjYLCv80mfRt0AWUBfrGo542tkQZCcTOvZBkuM6Uc3fZCGvMGFUmqEG3lVgl7WZCWdLtCHWi8MBjE61Nb7FGFb8p8ZB7JJ"}}' \
    http://localhost:3000/login
```

This is where the problem lies.

After POSTing my Facebook Access Token to Stormpath, the response I get back currently looks like this:

```console
< HTTP/1.1 200 OK
< X-Powered-By: Express
< Set-Cookie: idSiteSession=https://api.stormpath.com/v1/accounts/1qHd6ckEumu9aHA2Oe5ZRs; path=/; expires=Wed, 17 Feb 2016 00:22:56 GMT; httponly
< Date: Sat, 19 Dec 2015 00:22:56 GMT
< Connection: keep-alive
< Content-Length: 0
```

This doesn't make sense because:

- I'm not using idSite.
- I don't need the Account HREF -- I need an 'access_token' that I can store locally and use to authenticate against my express backend.

We should modify the login route code so that in situations like this, we:

- Return the Account data in the body of the response as JSON, per our spec.
- Set an 'access_token' (and maybe?) 'refresh_token' cookie that our developers can securely store and use in a traditional manner for authentication.

**Comment by robertjd** [comment]
A solution is in progress via #251

**Comment by robertjd** [comment]
This was done in 2.4.0
