### ISSUE TITLE
Can't disable web features

### ISSUE THREAD

**Issue by robertjd** [stormpath/express-stormpath#250]
If I use the `website: true` option, but also try to disable a specific feature, the feature is not disabled.

To reproduce, run this code, and see that the final config object has the value of `true` (not `false`) for `web.register.enabled`:

```
var express = require('express');
var stormpath = require('express-stormpath');

var app = express();

app.use(stormpath.init(app, {
  website: true,
  web: {
    register: {
      enabled: false
    }
  }
}));

app.on('stormpath.ready',function () {
  console.log(app.get('stormpathConfig').web.register);
});

```

@typerandom please prioritize this one.

**Comment by typerandom** [comment]
@robertjd I'll start working on this.

**Comment by ServCinc** [comment]
Thank you so much guys; I was the one who was having trouble with this! Hope you all had a great holiday!

**Comment by robertjd** [comment]
Happy to help!  I hope your holiday was good as well.  Be sure to watch this repo, for the next release (which will include this closed fix).
