### ISSUE TITLE
Replace "idSiteSession" cookie with Oauth tokens

### ISSUE THREAD

**Issue by robertjd** [stormpath/express-stormpath#251]
We have new features in the Stormpath API that allow us to:

* Exchange an ID Site result (the jwt that is delivered to the callback url) for an access token + refresh token pair.  Simply use `grant_type=stormpath_token` and `token=<jwt>` on the application's oauth token endpoint, where `<jwt>` is the jwt result from ID Site.

* For social login, use `grant_type=stormpath_token` and  `token=<jwt>`, where `<jwt>` has the same format as the id site result jwt, but the `iss` is the stormpath application that has serviced the social login attempt.  This jwt needs to be signed with a tenant api key.

**Comment by rdegges** [comment]
yesssss

**Comment by typerandom** [comment]
@robertjd Currently I've added a new grant type in the SDK to handle stormpath_token. But haven't been able to find how I should add this for social login. Could you explain this in more detail?

**Comment by robertjd** [comment]
After a user has returned from a social provider, and after we resolve the account with `application.getAccount()`, you can create a JWT with these claims:

```
{ 
  sub: 'https://api.stormpath.com/v1/accounts/:accountId',
  exp: 1453149681,
  iat: 1453149621,
  iss: 'https://api.stormpath.com/v1/applications/:applicationId',
  status: 'AUTHENTICATED',
  aud: 'client api key id' 
}
```

And then provide that for the `token` value in the `stormpath_token` grant type.   You can then pass that response to helpers/create-session.js.

**Comment by typerandom** [comment]
Thanks!

For clarity, are you referring to `login-responder.js` where `createIdSiteSession()` is being called? I.e. should that be replaced with a `"createStormpathSession()"` instead?

**Comment by robertjd** [comment]
Ah, yes!  It looks like some of this could be refactored as well.
