### ISSUE TITLE
preLoginHandler for logging

### ISSUE THREAD

**Issue by oekekezie** [stormpath/express-stormpath#259]
Right now I'm using the postLoginHandler to log successful login attempts. It would be great to have a similarly easy way to add logic to log all login attempts regardless of whether they succeed i.e. a preLoginHandler.

**Comment by timothyej** [comment]
Thanks for the feedback :)

How important is this feature to you? Would you be able to workaround it?

**Comment by oekekezie** [comment]
Very much a nice to have. Definitely able to work around it.

**Comment by timothyej** [comment]
That's great! If there's anything else, just let me know :)

**Comment by raoabishay** [comment]
I would love to see this feature as well. I'm trying to check if the user is already registered with us through other means[FB/Google] before logging them into the application. And if they are already logged in, the '/me' route could return the updated/merged data. This is possible only if we have something like a 'preLoginHandler'. Is it possible to implement this at all @timothyej ?
