### ISSUE TITLE
New body-parser helper resets the body, breaks middleware that expect streams

### ISSUE THREAD

**Issue by agonbina** [stormpath/express-stormpath#264]
Related to #256.

I'm using [rocky](https://github.com/h2non/rocky/) to proxy some of the routes of my express.js application, and using the `express-stormpath` library breaks the request body because the body-parser helper is "forcing" a default body of an empty object. The proxy expects the default body of an express request(a string or a buffer), so resetting the body to an empty object is breaking the request flow.

To fix this issue I commented out the following in `stormpath.js` in the sdk itself: 
```js 
router.use(bodyParser.forceDefaultBody())
```

Not sure if this breaks some other functionality(doesn't seem to) but I would say modifying the req.body on every request is not such a great idea anyway, so maybe there is a better way to handle this within the library?

**Comment by typerandom** [comment]
Thank you for reporting this issue. I just labeled this as a bug and I'm going to be looking into this shortly.

**Comment by robertjd** [comment]
I agree, our library should only modify `req.body` when we are parsing POST bodies for routes that our body binds to, such as `/register`, etc.
