### ISSUE TITLE
IDSite Automatic Configuration

### ISSUE THREAD

**Issue by rdegges** [stormpath/express-stormpath#267]
If you've got a configuration that looks like this:

```javascript
{
  web: {
    idSite: {
      enabled: true
    }
  }
}
```

And you attempt to visit `/login`, `/logout`, or `/register`, you'll get a 404. This is because as of right now, you need to **explicitly** enable register / login / logout in the `web` section in order for this to take place.

The desired behavior is actually the opposite: if IDSite is enabled, we want to *always* provide the IDsite routes regardless of what the register / login / logout / verification / etc. settings are currently set to.

Fixing this issue will make our documentation for ID site valid again, as right now it is incorrect.

**Comment by typerandom** [comment]
Closing this since now `/login`, `/logout` and `/register` is enabled by default.
