### ISSUE TITLE
OAuth Policy TTLs Not Respected

### ISSUE THREAD

**Issue by rdegges** [stormpath/express-stormpath#270]
It appears that at some point we broken OAuth Policy TTL functionality.

Here's an example Express app that shows how to reproduce this. The way it works is simple: create a Stormpath Application, and set the access token and / or refresh token TTLs to a custom value.

When you log into the website (localhost:3000), you'll see the token debug information, as well as the TTL settings. They always end up at 3600 regardless of what is set.

```javascript
var cookieParser = require('cookie-parser')
var express = require('express');
var jwt = require('njwt');
var stormpath = require('express-stormpath');

var app = express();

app.use(stormpath.init(app, {
  application: {
    href: 'https://api.stormpath.com/v1/applications/xxx'
  },
  website: true
}));

app.use(cookieParser());

app.get('/', stormpath.loginRequired, (req, res) => {
  var accessToken = jwt.create(req.cookies.access_token);
  var refreshToken = jwt.create(req.cookies.refresh_token);

  res.json({
    accessToken: accessToken.compact(),
    accessTokenIssueTime: accessToken.body.iat,
    accessTokenExpirationTime: accessToken.body.exp,
    accessTokenTTL: accessToken.body.exp - accessToken.body.iat,
    refreshToken: refreshToken.compact(),
    refreshTokenIssueTime: refreshToken.body.iat,
    refreshTokenExpirationTime: refreshToken.body.exp,
    refreshTokenTTL: refreshToken.body.exp - refreshToken.body.iat
  });
});

app.on('stormpath.ready', () => {
  app.listen(3000);
  console.log('Server running!');
});
```

<img width="1274" alt="screenshot 2016-01-18 10 38 16" src="https://cloud.githubusercontent.com/assets/90247/12399564/a077dbec-bdcf-11e5-957d-f6aa007c89e3.png">

**Comment by areichman** [comment]
@rdegges You can recreate the issue using just the Stormpath Node SDK. The Express additions here are not required. It might make sense to track the issue there instead, but that's up to you.  Thanks for digging into it for me either way.

```javascript
application.authenticateAccount({username: req.body.username, password: req.body.password}, function(err, authResult) {
  var jwt = authResult.getJwt();
  // jwt still has a 3600 second TTL
})
```

**Comment by robertjd** [comment]
@rdegges in your example, you are using the nJwt library to create JWTs correctly.  If you want to change the TTL of those JWTs, you have to use the interface of the nJwt library.  See [here](https://github.com/jwtk/njwt#expiration-claim).

If you want to create tokens with the context of the application's OAuth policy, you need to use the `OAuthPasswordGrantRequestAuthenticator` in the way that you see in [login.js](login.js).
