### ISSUE TITLE
Using BodyParser (URLencoded) Breaks Stormpath

### ISSUE THREAD

**Issue by rdegges** [stormpath/express-stormpath#274]
If you load the `bodyParser.urlencoded(...);` middleware BEFORE the Stormpath middleware, the library breaks on registration / login. When the form is submitted, the server hangs indefinitely.

**Comment by timothyej** [comment]
Isn't this a duplicate of #194?

**Comment by rdegges** [comment]
Oh, good catch. Somehow didn't see that :x
