### ISSUE TITLE
/logout doesn't invalidate the account cache

### ISSUE THREAD

**Issue by typerandom** [stormpath/express-stormpath#278]
When logging out using `/logout` the account cache isn't invalidated.

#### How to reproduce

1. Setup a new Node.js project using [this gist](https://gist.github.com/typerandom/7833f2cebbad57072310).
2. Create a new account (/register).
3. Login with the account (/login).
4. Set `customData.myValue` to `true` using the Stormpath Admin console. 
5. Logout (/logout.) 
6. Login (/login).

#### Actual

Server prints `myValue undefined` to console.

#### Expected

Server prints `myValue true` to console.

**Comment by robertjd** [comment]
This *is* the expected behavior from the cache manager of the underlying client (it keeps the cache entry, until it expires).  We don't yet have a way to notify clients of an updated resource.  As such, invalidating the cache on logout would be a nice workaround for now.
