### ISSUE TITLE
Very slow

### ISSUE THREAD

**Issue by lillereven** [stormpath/express-stormpath#279]
Repeatable performance problem on my machine. Views loading with Express-Stormpath in the mix in 600ms+. If I comment out Express-Stormpath, things load in under 50ms, as I would expect from a JADE-driven site loading from localhost.

What could I be missing?

I tried adding cacheOptions for the in-memory store, to no avail.

My runtimes:
node 5.5.0
npm 3.3.12
express-stormpath 2.3.6

**Comment by lillereven** [comment]
After moving my partial and asset routes out of the Stormpath routing scope, performance is OK. Could it be that express-stormpath is not using the in-memory caching instance?

**Comment by robertjd** [comment]
Hi there, thanks for getting in touch!  Yes, `stormpath.init()` does apply our authentication layer to the Express application (or router) that is passed to it.  As such, you'll see an authentication ovehread on your public asset routes if you pass that appplication/router to `stormpath.init()`.  The solution is to use `stormpath.init()` after you have defined any public asset middleware.

I apologize for the confusion here.  This is something I'd like to change, I've opened a discussion in #285 .

Best,
Robert
