### ISSUE TITLE
Any way to configure express-stormpath to use a different template location?

### ISSUE THREAD

**Issue by lillereven** [stormpath/express-stormpath#283]
Not an issue, but a question/feature request.

I like the pre-built templates, and and to edit/change/version control them. As things are right now, and I admit to not having inspected the code very deeply, those templates live within node_modules/express-stormpath/lib/views - not the best location to tool around in.

Is there a config option to point express-stormpath at a different folder within my app setup so I can easily version-control the template location?

Thanks,
Martin

**Comment by robertjd** [comment]
Hi Martin, we do allow you to specify the location of custom templates.  Pleas see the documentation here:

http://docs.stormpath.com/nodejs/express/latest/templates.html
