### ISSUE TITLE
Don't apply `getUser` middleware to passed app

### ISSUE THREAD

**Issue by robertjd** [stormpath/express-stormpath#285]
By default, we will attach the `getUser` middleware to all requests on the application or router instance that is passed into `stormpath.init()`, as seen here:

https://github.com/stormpath/express-stormpath/blob/master/lib/stormpath.js#L219

As such, we force all requests through our authentication layer and this adds network overhead when you're logged in.  If you accidentally apply our module to your "public" folder (static assets, etc), a folder that doesn't require authentication, you app becomes unexpectedly slow.  Myself and other develoeprs have run into this many times.

Should we be doing this?  

My opinion is that `stormpath.init()` not apply authentication middleware.  We provide explicit middleware functions, such as `stormpath.loginRequired`.  As such we should allow the developer to tell us what routes that they want protected.

**Comment by lillereven** [comment]
+1 explicit middleware-only

As a programmer who has fallen into this trap recently, I support the vote for only using the explicit ExpressJS middlewares. After all, you are providing a very good set of middlewares to work with, such as loginRequired or groupRequired, and it is very easy to develop custom middlewares when needed for a project.

**Comment by typerandom** [comment]
I fully agree here on only applying middlewares explicitly.

**Comment by robertjd** [comment]
Thanks all for the input!  Let's make this change.  I've changed the title of this issue, I'm going to add it the 3.0 milestone.
