### ISSUE TITLE
POST request hangs if body-parser is configured

### ISSUE THREAD

**Issue by typerandom** [stormpath/express-stormpath#289]
If the `body-parser` module is configured with express as `app.use(bodyParser.urlencoded({ extended: true }));` then any POST requests handled by `express-stormpath` hangs.

#### How to reproduce

1. Create a new server using [this gist](https://gist.github.com/typerandom/b1178002a81751b82923).
2. Start the server.
3. Navigate to [/register](http://localhost:3000/register).
4. Sign up for a new account.

#### Actual

Page hangs indefinitely.

#### Expected

Page is redirected to [/login?status=verified](http://localhost:3000/login?status=verified). If you have email verification turned on, then it should redirect to [/login?status=unverified](http://localhost:3000/login?status=unverified).

**Comment by timothyej** [comment]
I've reported the same problem here (as a comment): #194
