### ISSUE TITLE
Multi-tenancy support

### ISSUE THREAD

**Issue by robertjd** [stormpath/express-stormpath#292]
We need to add multi-tenancy support to this library, using our Organization model.  This will affect how the login and registration controllers operate.  This task needs more definition, but the essence is that it will mirror how we handle organizations for ID Site.

Note: we also need to ensure that we give some options that allow the developer to specify account stores, to help those who are using directories to segment environments.

**Comment by omgitstom** [comment]
There also should be simple middleware to help authorize that the account is in the resolved organization

**Comment by cmberard** [comment]
Would it be possible for this to encompass API requests as well as username/password users? 

Currently even using the the Node SDK there isn't a simple way to authenticate an API request against a particular account store. Application.authenticateAccount allows passing an accountStore, but Application.authenticateApiRequest does not.

**Comment by robertjd** [comment]
Hi @cmberard , thank you for the input.  Yes, we want to allow you to make organization-based decisions, regardless of the authentication mechanism.  Can you tell me which authentication flow(s) you are using authenitcateApiRequest for?  E.g. HTTP Basic Auth, or the Client Credentials OAuth flow?  Just curious to know which one(s) is/are important to you.  Thanks!

**Comment by cmberard** [comment]
@robertjd We're actually allowing both Basic & Client Credentials OAuth for API users right now. Main reason is that I don't have an easy way to distinguish between the two in Stormpath since they both use apiAuthenticationRequired (at least as far as I'm aware).

The way we are set up, if I just had the ability to expand the Organization on req.user, I'd be able to validate that against the host and/or environment variables to validate. Thanks for your help, btw, this module is super useful to me and my team!

**Comment by mdeggies** [comment]
Any updates on this?

**Comment by tanzim** [comment]
As @mdeggies said :)

**Comment by robertjd** [comment]
We are starting work on this now :)  The feature has been designed here: https://github.com/stormpath/stormpath-framework-spec/blob/master/multi-tenancy.md

**Comment by tanzim** [comment]
@robertjd great to know :) I didn't see anything in the docs talking about specifying account stores? Is that in scope? I ask because of #470.  
Thanks.

**Comment by robertjd** [comment]
Hi @tanzim , yes we're focusing on Organizations at the supported mechanism.  But you'll be able to replace the organization resolver with your own resolver (a simple function), and it can return the account store that you need to use (rather than an organization).
