### ISSUE TITLE
Implement JSON view model for GET on /login

### ISSUE THREAD

**Issue by timothyej** [stormpath/express-stormpath#306]
Implement JSON view model for GET on `/login` according to the [framework spec](https://github.com/stormpath/stormpath-framework-spec):

> ## View Models
> 
> The login an registration views are dynamic.  The registration form has
> configurable fields, and both login and registration need to dynamically render
> buttons for any providers (Google, Facebook, SAML) that are mapped to the
> specified Stormpath application.
> 
> For that reason, we support JSON GET requests of the `/login` and `/register`
> views.  The response is a view model that the client can use to render the
> form appropriately.
> 
> Please see [login](https://github.com/stormpath/stormpath-framework-spec/blob/master/login.md) and [registration](https://github.com/stormpath/stormpath-framework-spec/blob/master/registration.md) for specific information on each
> model.

Part of #298.

**Comment by timothyej** [comment]
@robertjd, why would we want to include the form fields in the view model for `/login`? Wouldn't it always be username and password? Or will it possible to add organization as well?

**Comment by typerandom** [comment]
@timothyej I think the idea is that since [it's configurable](https://github.com/stormpath/stormpath-framework-spec/blob/master/web-config.yaml#L128) it needs to expose those values. I.e. maybe someone wants the placeholder to only be "Email" instead of "Username or Email".

**Comment by timothyej** [comment]
Thanks @typerandom, I had some guesses about that too, but it's not really clear. If this turns out to be correct, I will probably clarify that in the specs.

**Comment by robertjd** [comment]
Yes, fields are configurable and will be extended by multi tenancy support.
