### ISSUE TITLE
/change forwards to /forgot

### ISSUE THREAD

**Issue by jonathan-fielding** [stormpath/express-stormpath#311]
Hi

When I am logged in I expect to got to /change to change my password but unfortunately I simply get forwarded to /forgot. This is my config:

```
app.use(stormpath.init(app, {
    website: true,
    web: {
        register: {
            autoLogin: true,
            nextUri: '/'
        }
    },
    expand: {
        customData: true
    }
}));
```

Thanks

Jonathan

**Comment by jonathan-fielding** [comment]
Tested this on both facebook auth and normal login

**Comment by lillereven** [comment]
Same here. I am on version 2.4.0.

**Comment by robertjd** [comment]
Hey all!  This is, actually, the intended behaviour.  The /change route is meant to be used when you are not logged in, and you have arrived on the route with a password reset token that has been emailed to you.

At the moment our library does not provide a change-password form for authenticated users.  We found that most developers have a lot of customization around this, so we left it out of the core library.

However it's super easy to implement.  Please take a look a the code that handles the profile page for our [Express-Stormpath Example Project](https://github.com/stormpath/express-stormpath-sample-project).  You can use the same code, and just add a password field as well.

Hope this helps!

**Comment by jonathan-fielding** [comment]
Would be nice to have a change password page or a profile page built in even if its disabled by default
