### ISSUE TITLE
Social login not compliant to spec

### ISSUE THREAD

**Issue by edjiang** [stormpath/express-stormpath#362]
Testing against `framework-spec-upgrade` branch.

In https://github.com/stormpath/stormpath-framework-spec/blob/master/login.md:

It says to post:

```
{"providerId": "facebook",
    "accessToken": TOKENHERE"
}
```

But `express-stormpath` only responds to:

```
{"providerData": {"providerId": "facebook",
    "accessToken": "TOKENHERE"
}}
```

Which is correct?

**Comment by robertjd** [comment]
Spec was modified to mirror the express implementation, as this is the one that we want to use for all integrations.
