### ISSUE TITLE
Stormpath sibling dependency breaks apiKey option

### ISSUE THREAD

**Issue by robertjd** [stormpath/express-stormpath#375]
This is a strange one, @typerandom can you confirm this reproduction?

Create a new node app, with the following package.json:

```
{
  "name": "test",
  "main": "server.js",
  "dependencies": {
    "express": "~4.10.0",
    "express-stormpath": "^3.0.1",
    "stormpath": "^0.17.5"
  }
}
```

Install the modules, then run this server with some valid credentials and an application, and put them into the code as seen here:

```
var express = require('express');
var stormpath = require('express-stormpath');

var app = express();

app.use(stormpath.init(app, {
  apiKey : {
    id: 'xxx',
    secret: 'xxx'
  },
  application: {
    href: 'xxx'
  }
}));

app.on('stormpath.ready',function(){
  console.log('Stormpath Ready');
});
```

I get the error  `Error: API key ID and secret is required.`

Then I do the following:
* Remove stormpath from package.json
* Delete the node_modules folder
* npm install

Then I run server.js again, and it works: they keys are accepted, and Stormpath initializes.

**Comment by schamp** [comment]
I was seeing something like this, but I tried running 
`npm shrinkwrap`
and then it went away.  But I haven't tried restarting the service since then, not wanting to push my luck.

**Comment by typerandom** [comment]
@robertjd I'm looking into this. It sounds very weird, like there's an old dependency (either linked) or fixed (with shrinkwrap) that is causing it... But I'm going to try myself and see if it's reproducable.

**Comment by typerandom** [comment]
I just tried this and I wasn't able to reproduce the issue. I got the `Stormpath Ready` message immediately.

**Comment by robertjd** [comment]
Did you make sure that you don't have your API keys specified elsewhere,
such as environment variables, yaml files, or properties files in your
homedir?

**Comment by typerandom** [comment]
I didn't. But I tried first running the application href as 'xxx' and that threw an error, then I ran the api key with 'xxx' and it threw an error. Then I replaced the values with real ones. And then it worked.

@robertjd If you do the steps, are you able to replicate the error each time?

**Comment by robertjd** [comment]
@typerandom and I just dug into this, and we think it's an issue with npm 2.x - we can reproduce my problem there, but not with 3.x.

@schamp can you tell us what npm version(s) you're using?  Thanks!

**Comment by schamp** [comment]
I'm running on a cloud foundry container, the NPM version I have appears to be 2.14.9

**Comment by robertjd** [comment]
I'm going to close this issue for now, we've found several instances where upgrading to NPM 3.x will resolve the problem.  I'd still like to know why our library can get into this edge case, but this NPM workaround is acceptable for now.
