### ISSUE TITLE
custom logger is ignored

### ISSUE THREAD

**Issue by balsamiqstefano** [stormpath/express-stormpath#383]
I'm passing a "logger" parameter (a Winston logger) to stormpath.init, but it looks like it's being ignored and the log keeps going to the console using the fallback defined in lib/stormpath.js line 33.

I think the problem resides in the fact that "stormpathLogger" is read via an "app.get" at line 30, but there was never an "app.set" call before.

For the moment I worked around the issue by explicitly calling "app.set('stormpathLogger", ...)" before calling "stormpath.init", but this looks like a bug to be fixed, if I'm not wrong.

**Comment by robertjd** [comment]
Thanks @balsamiqstefano !  This is broken, I've opened a PR to fix it.
