### ISSUE TITLE
sptoken in password reset link not validated

### ISSUE THREAD

**Issue by stevebread** [stormpath/express-stormpath#385]
I'm using express-stormpath 3.0.1 and angular sdk 1.0.0. On loading the password reset page, the angular sdk makes a GET request of the form `http://localhost:9000/change?sptoken=...`. This request always returns the index.html page regardless of the value of sptoken which the angular sdk interprets as a successful response and then shows the password reset form.

The password change submission does not work unless the sptoken value is valid.

**Comment by robertjd** [comment]
Thanks @stevebread !  I was able to confirm this bug and have an open PR to fix it.

**Comment by stevebread** [comment]
Thanks @robertjd . I upgraded to 3.1.1 but now when I click on the email link the server always returns an error `{"status":400,"message":"passwordResetTokens password is an invalid type."}`

**Comment by robertjd** [comment]
D'oh!  You're right, we fixed the invalid token case, but broke the valid token case.  I've opened #403 with another fix, and more tests to ensure that we don't break this in the future - sorry about that!

**Comment by robertjd** [comment]
Hi @stevebread , can you try the new 3.1.2 release?  This should be fixed for good now :)

**Comment by stevebread** [comment]
3.1.2 is all good! Thanks @robertjd !
