### ISSUE TITLE
postLoginHandler: changes to customData are discarded

### ISSUE THREAD

**Issue by nitzanshinnies** [stormpath/express-stormpath#391]
I'm trying to add data to the customData object (it's expanded)

-------------------------
postLoginHandler: function (account, req, res, next) {
req.user.getCustomData(function(err, data) {
[setting various properties]

data.save(function() { 
req.user.customData=data;
next();
});

-------------------------

however, the new properties are discarded - they don't show either in the req.user object or stormpath user management. If I set these properties somewhere else, then the changes are saved.

Please advise. Thanks!

**Comment by robertjd** [comment]
Hello @nitzanshinnies , I wanted to make sure that you were able to get around this error?  It looks like the problem was that you were trying to modify the custom data from inside the save function, but it needs to go outside of it.  Let us know, always happy to help!

**Comment by nitzanshinnies** [comment]
@robertjd Yes, sorry. My bad. The culprit was an object key that contained a space.
