### ISSUE TITLE
YAML not working

### ISSUE THREAD

**Issue by radleymith** [stormpath/express-stormpath#392]
Within the past few days, an update to stormpath, stormpath-config, or express-stormpath has caused the stormpath.init(app, {/*someConfig*/}); function to not be able to read my yaml file.  I'm currently trying to hunt down the root cause in the commit history, but if someone closer to the source knows more information I'd appreciate it.  I can still get my app to run by exporting the id, secret, and href.  I'd just rather use the yaml.

**Comment by radleymith** [comment]
I should probably open this with stormpath-config instead, I think I know (roughly) where the error is... it's related to getting the correct directory expansion for finding the YAML file.

**Comment by robertjd** [comment]
Hi @radleymith could you take a look at #375?  We do have an issue with sibling dependencies and NPM versions, I wonder if this is true for your case.  Thanks!

**Comment by radleymith** [comment]
My npm version has always been 3.3.*.  You might be on to something with the sibling dependency, but the only things I've added to my package.json are redux and react-redux.

**Comment by radleymith** [comment]
I've also opened an issue on stormpath-node-config because it seems like the process that looks for and loads the stormpath.yml is looking in the wrong directory(inside the node_modules directory).

**Comment by robertjd** [comment]
Thanks for looking into this with us!  Can you show me what your stormpath module structure looks like with `npm ls | grep stormpath`?  Mine looks like this:

```
stormpath-express-profile-example@1.0.0 /Users/robert/projects/express-stormpath-sample-project
├─┬ express-stormpath@3.0.1
│ ├─┬ stormpath@0.17.5
│ ├─┬ stormpath-config@0.0.22
```

That is what I get at the root of our [express-stormpath-sample-project](https://github.com/stormpath/express-stormpath-sample-project), and with this project I'm able to use my stormpath.yaml file. It's in the root of the sample project folder and looks like this:

```yaml
client:
  apiKey:
    id: xxx
    secret: xxx
application:
  href: https://api.stormpath.com/v1/applications/xxx
```

I'm using Node v0.12.2 and NPM 3.8.2

Thanks!

**Comment by radleymith** [comment]
Sure my stormpath module structure...
```
├─┬ express-stormpath@3.0.1
│ ├─┬ stormpath-config@0.0.22
├── react-stormpath@1.0.0
├─┬ stormpath@0.17.5
```
My stormpath.yaml
```
client:
  apiKey:
    id:my_id
    secret:my_secret
application:
  href:https://api.stormpath.com/v1/applications/my_app
```
I'm using Node v5.5.0 and NPM 3.3.12

**Comment by robertjd** [comment]
Thanks!  I see that in your configuration, the `stormpath` dependency has been moved up the tree - that may be a clue for us as we debug.  Are you using a shrinkwrap file to achieve this structure?

**Comment by radleymith** [comment]
I'm not using shrinkwrap

**Comment by typerandom** [comment]
I have opened a PR that I think should fix this issue. See:
https://github.com/stormpath/stormpath-node-config/pull/46

**Comment by typerandom** [comment]
Issue has been solved. Was due to YAML file not properly setup. Closing.
