### ISSUE TITLE
Degraded performance after upgrading from 3.0.1 to 3.1.0

### ISSUE THREAD

**Issue by cgilindellmo** [stormpath/express-stormpath#397]
Hi,

We've experiencing significant slowdowns in our application after upgrading from 3.0.1 to 3.1.0. Our Mocha tests started to timeout as requests take much longer than before. We authenticate using /oauth/token (password) authentication mechanism.

We're using the following Stormpath middleware's for our routes:
stormpath.apiAuthenticationRequired, stormpath.getUser

Only configuration change for the upgrade was the addition of web.register.form.fields.confirmPassword.enabled

If we rollback to 3.0.1, the slowdown is gone. Can you confirm this?

Thanks,
Matti Lindell

**Comment by robertjd** [comment]
Hello @cgilindellmo , can you tell me which [token authentication strategy](http://docs.stormpath.com/nodejs/express/latest/authentication.html#token-validation-strategy) you are using? `stormpath` or `local`?  If you are using `stormpath`, that will explain the slowdown: in 3.1.0 we fixed `apiAuthenticationRequired` to respect the `stormpath` option, and make a roundtrip call to our API on every authentication attempt.

**Comment by cgilindellmo** [comment]
We've explicitly defined local token auth strategy (although it's documented as the default).

Thanks,
Matti

**Comment by cgilindellmo** [comment]
Here's the config:

stormpath.init(app, {
    debug: 'info, error',
    web: {
      me: {
        enabled: false
      },
      oauth2: {
        password: {
          validationStrategy: 'local'
        }
      },
      register: {
        form: {
          fields: {
            confirmPassword: {
              enabled: true
            }
          }
        }
      }
    }
  });

**Comment by robertjd** [comment]
Thanks!  I see where the problem is, I forgot to carry the strategy option into a part of this refactor :( I'll make a patch release today, sorry about this!

**Comment by robertjd** [comment]
I've published 3.1.1, which should fix this issue.  @cgilindellmo can you please try?  Thanks!

**Comment by cgilindellmo** [comment]
It's good now, thanks!

**Comment by robertjd** [comment]
Awesome!
