### ISSUE TITLE
how to force authentication on all routes

### ISSUE THREAD

**Issue by jmls** [stormpath/express-stormpath#40]
I've followed the quickstart guide (and, may I say, great job!) and got auth working just fine on certain routes.

however, I'm a little stuck on how to ensure that authentication is done on all routes, even static ones.

I have this in my app

app.use(loopback.static(path.resolve(__dirname, '../client')));

how can I force a user to login before accessing the site ?

thanks !

**Comment by dorukeker** [comment]
Hello,
I am not using the strongloop and I got a similar issue. But I also found the cause in my case. I am sharing here so it might help some.

I was initialising the StormPath after I use my router and it did cause trouble. When I switched places it worked fine.

Here are two of the case.
Not working (giving the redirect loop):

    var express = require('express');
    var app = express();
    var routes = require('./routes/routes');
    app.use(routes);
    app.use(stormpath.init(....));

Working one:

    var express = require('express');
    var app = express();
    app.use(stormpath.init(....)); // Notice the init is called before routing.
    var routes = require('./routes/routes');
    app.use(routes);
    
Hope that helps some one.
Cheers!

**Comment by lanbau** [comment]
thanks @dorukeker i managed to solve my app's redirect loop error. My routes were above stormpath.init
