### ISSUE TITLE
GroupsRequired does not work with JSON

### ISSUE THREAD

**Issue by edjiang** [stormpath/express-stormpath#408]
For:

```
app.get('/test', stormpath.groupsRequired(['admins']), function(req, res) {
```

```
GET /test
Accept: application/json

HTTP/1.1 302 Found
X-Powered-By: Express
Location: /login?next=%2Ftest
Vary: Accept
Content-Length: 0
Date: Fri, 01 Apr 2016 19:20:37 GMT
Connection: close
```

I expect to get `401 Unauthorized` instead. 

If I authenticate with a valid access token but without the correct group: 

```
GET /test
Accept: application/json
Authorization: Bearer VALIDTOKEN

HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: text/html; charset=utf-8
Content-Length: 12181
ETag: W/"2f95-RuQEqVCsRcmcGl7IB/xhmQ"
Date: Fri, 01 Apr 2016 19:23:21 GMT
Connection: close
```
<img width="636" alt="screen shot 2016-04-01 at 12 25 47 pm" src="https://cloud.githubusercontent.com/assets/918770/14217776/e66e5544-f804-11e5-8f98-58125e9fcfcb.png">

I expect to get `403 Forbidden` instead. 

With a user in the correct group and everything, things work as expected.

**Comment by edjiang** [comment]
I'm writing this into the framework spec, but in general right now I think all middleware need to be inspecting the Accept: header and doing content negotiation.

**Comment by h3xc0ntr0l** [comment]
does anyone have any news on this? I'm having the exact same issue
