### ISSUE TITLE
Unable to login using Google Social Login with online access 

### ISSUE THREAD

**Issue by cgilindellmo** [stormpath/express-stormpath#410]
Hi,
I'm able to login using Google as OAuth provider, but only with 'offline' access (providerData contains code). The 'online' access (providerData contains accessToken) fails in Stormpath's end, even though I'm supposedly doing things correctly. Could you verify that the online access in Stormpath's is working correctly?

I'm using JSON API method as described in https://docs.stormpath.com/nodejs/express/latest/social_login.html

Thanks,
Matti

**Comment by edjiang** [comment]
Hey Matti,

I just tried Google Login with Express-Stormpath 3.1.2, and I'm confirming that it's working fine for me with the following permissions: 

![screen shot 2016-04-04 at 11 08 53 am](https://cloud.githubusercontent.com/assets/918770/14258087/a688bc28-fa55-11e5-8b5c-1d981c1b9f94.png)

How are you generating the access token? I'm guessing you're using a Google SDK?

**Comment by robertjd** [comment]
Hi Matti, can you also show us the scope string that you are passing to Google?  In our library, this is configured with the `web.social.google.scope` property.  I see that this new property is not documented, I've added this to our todo list in #380 - sorry about that!

**Comment by cgilindellmo** [comment]
Hi,
I should have opened this against the stormpath node.js module as I'm using [getAccount(providerOptions, [options,] callback)](http://docs.stormpath.com/nodejs/api/application#getAccount) function to implement Social Login as express-stormpath's implementation doesn't suit well for api-based social login (client's are mobile devices).

So I'm able to get this working:
`var options = {
  providerData: {
    providerId: 'google',
    **code**: 'abc1235'
  }
};`

But not this one:
var options = {
  providerData: {
    providerId: 'google',
    **accessToken**: 'abc1235'
  }
};

This is can be a misconfiguration from my part, but I'd like you to confirm if the latter is confirmed as working with application.getAccount.

Thanks,
Matti

**Comment by edjiang** [comment]
Hey Matti,

Yes, both of these should be valid. I work @ Stormpath on the iOS side. Can you tell us a little more about how you're doing mobile? 

If you haven't already seen it, our iOS and Android SDKs will plug into Express-Stormpath and make mobile auth just work. 

If you want to handle it manually -- can you please tell me which OS & client library you're using to get the Google Access Token? 

Google has this thing called the ID Token which is different from the access token. If you see [Google's documentation](https://developers.google.com/identity/sign-in/ios/api/interface_g_i_d_authentication#properties), there's both the ID Token and access token. Make sure you're sending the access token to Stormpath.

**Comment by cgilindellmo** [comment]
Hi edjiang,

I'm doing the Google OAuth on iOS side using [GoogleSignIn](https://cocoapods.org/pods/GoogleSignIn) version 3.0.0. Google's docs are bit outdated for v3.0.0, but I've understood that when I define
- only `GIDSignIn.sharedInstance().clientID` in AppDelegate, then Google provides `user.authentication.idToken` as successful sign-in (which I can provide as `accessToken` for Stormpath's `getAccount` ?)
- both `GIDSignIn.sharedInstance().clientID` and `GIDSignIn.sharedInstance().serverClientID` in AppDelegate, then Google provides `user.serverAuthCode` after successful sign-in (which I provide as `code` for Stormpath's `getAccount` and the offline login works okay)

Thanks,
Matti

**Comment by cgilindellmo** [comment]
Correction to the above: I'm actually POSTing `providerData` to /login endpoint as you noted.

**Comment by cgilindellmo** [comment]
Hmm I might have read Google's specs wrong, https://developers.google.com/identity/sign-in/ios/api/interface_g_i_d_authentication#instance-method-summary actually defines **accessToken**, idToken is meant for OpenId.

I'll test this out and close the issue with my regrets if this now works..

**Comment by edjiang** [comment]
Yep, you should be using user.authentication.accessToken instead. 

If you're doing this, I would suggest trying our iOS SDK! We actually implement all of this for you, saving quite a bit of work =]

https://github.com/stormpath/stormpath-sdk-ios

**Comment by cgilindellmo** [comment]
Thanks! (and sorry about this) I'll close the ticket.
