### ISSUE TITLE
access token and refresh token name not respected

### ISSUE THREAD

**Issue by martinbooth** [stormpath/express-stormpath#411]
I have changed the names of the access token/refresh token as per the config. This is because we run both the dev and prod site under the same domain and don't want the cookies overwritten by each.

The settings for accesstoken and refreshtoken name affect the name of the cookies created, however the code is hard coded to read cookies with the names access_token and refresh_token, not respecting the configured name:

https://github.com/stormpath/express-stormpath/blob/10252505b7c4602e52771fb65656b9e73937f598/lib/helpers/get-user.js#L50

**Comment by robertjd** [comment]
Thanks for finding this!  I'm going to open this up for our next release.

**Comment by robertjd** [comment]
Thanks @martinbooth ! I brought your branch to our repo so that tests can run in Travis, and added you to the contributors file :) This will go out in the next release.
