### ISSUE TITLE
Create Custom fields name issue

### ISSUE THREAD

**Issue by cgilindellmo** [stormpath/express-stormpath#414]
Hi,

[Creating Custom Fields](https://docs.stormpath.com/nodejs/express/latest/registration.html#creating-custom-fields) suggests that "**name** - The name of this field, in the form model that is posted to the server." Does this work as documented as the submitted value is not bound to the name value I'm setting in the model when looking formData in preRegistrationHandler's ?

With the following I see the value in preRegistrationHandler to be 'foo,' but I'd expect it to be 'bar'?
```
foo: {
  enabled: true,
  label: 'Test',
  name: 'bar',
  required: true,
  type: 'text'
}
```

Thanks,
Matti

**Comment by robertjd** [comment]
Thanks for the report, we'll look into this.  It should be 'bar' as you expect.

**Comment by edjiang** [comment]
@robertjd, I thought we changed it so the name field is no longer required, and is instead based on the property label like `foo`? 

https://github.com/stormpath/stormpath-framework-spec/commit/01d8745bb46cea6b6f6204732e7d235b064f20cd#diff-38a8983f478dea556d71617301415c7f

**Comment by typerandom** [comment]
According to spec it should be kept as it is.

@robertjd Any input here?

**Comment by robertjd** [comment]
Correct, we did change this such that the name field is implied by the field definition property, I'm updating the docs in #453, @typerandom please review
