### ISSUE TITLE
User cannot login after account verified

### ISSUE THREAD

**Issue by erwanjegouzo** [stormpath/express-stormpath#416]
Hi,
I setup my stormpath application to enforce email verification, but I can't login, even after verifying the account. I'm using 3.1.2.

Steps to reproduce:
1/ Create an account
2/ Click on the verification link
3/ Go to the login page and submit the login form
4/ The page was submitted but the user not logged. Login form is displayed again.

What I noticed, is that if I restart my nodeJs app, the user can login.
Also, the account object returned from `authenticationResult.getAccount` has the status property as `UNVERIFIED` even though it's displayed as enabled in the stormpath dashboard.

**Comment by robertjd** [comment]
Hi @erwanjegouzo 

For the directory in question, can you tell me what the link base URL is?  By default it points to a placeholder page on our domain, and when you verify there it will be out of sync with the cache in your Express application.  The link base URL needs to point to your application, and it is documented here:

http://docs.stormpath.com/nodejs/express/latest/registration.html#email-verification

Thanks!

**Comment by erwanjegouzo** [comment]
Awesome, thank you!
