### ISSUE TITLE
stormpathConfig.web.forgotPassword.enabled doesn't work

### ISSUE THREAD

**Issue by cgilindellmo** [stormpath/express-stormpath#424]
Hi,

I'm trying to disable "Forgot password?" link in login form, but the configuration option stormpathConfig.web.forgotPassword.enabled doesn't work.

I'm able to disable registration without issues.

 ```
stormpath.init(app, {
    web: {
      forgotPassword: { enabled: false },
      changePassword: { enabled: false },
      register: { enabled: false }
    }
  });
```

Is there something I'm doing wrong or is this a bug?

Thanks,
Matti

**Comment by robertjd** [comment]
Hi Matti, thanks for this report!  I can confirm this problem, this is a bug and we'll be looking into it ASAP.

**Comment by robertjd** [comment]
@cgilindellmo we fixed the issue in the underlying configuration parser, that dependency is now updated in master and I'll try for a release this week - we have a handful of other bugs we're fixing so it will be nice to get this all out as one release.  Thanks again for the report!
