### ISSUE TITLE
Google OAuth directory corrupts?

### ISSUE THREAD

**Issue by cgilindellmo** [stormpath/express-stormpath#432]
Hi,

We're having an issue where Google OAuth suddenly stops working and gives error:
"The specified accessToken is not intended to be consumed by the Google directory mapped to this application."

We fixed this by creating a new Google OAuth Directory with exact same properties and mapped it to the application instead of the non-working one, and it fixed the issue. There has been no code changes on the client side.

Can you confirm this issue? Broken Directory in our account is called "Google OAuth" and the working one "Google OAuth (new)"

Thanks,
Matti

**Comment by robertjd** [comment]
Thanks for the report, we can take a look at the directory but you'll need to invite us to your tenant first.  Please contact us through support@stormpath.com and we'll send you instructions.  Thanks!

**Comment by cgilindellmo** [comment]
This was resolved some time ago and can be closed, thanks!
