### ISSUE TITLE
BodyParser breaks registration in 3.1.2

### ISSUE THREAD

**Issue by AlstonLin** [stormpath/express-stormpath#442]
Specifically, adding `app.use(bodyParser.json());` causes any Registration attempts to fail and giving a message "First Name required." from the server.

Probably related to #436

**Comment by edjiang** [comment]
Hey Alston,

For the meantime, you can put bodyParser after `app.use(stormpath.init(app, {...}))` and it should work

**Comment by AlstonLin** [comment]
Putting bodyParser after the init line works. Thanks!

**Comment by robertjd** [comment]
Thanks all, I'm closing this as s duplicate of #436
