### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by LamourBt** [stormpath/express-stormpath#456]
Issue has been solved

**Comment by edjiang** [comment]
Glad things have been resolved! I'll close this issue, then! =]

**Comment by LamourBt** [comment]
@edjiang how would I be able to disable the back door pages **/login /register/ logout** of stormpath. ** {website:false}** is that the permanent way of doing it. I am asking this because my plan is only to use the api key and secret key of the user account either in PostMan or in the mobile app. 

Do you have happen to have the configuration example for PostMan because they are asking Auth URL, Access Token URL, Token Name,Grant Type and the only thing that stormpath provides is the client ID and Client Secret

**Comment by edjiang** [comment]
To use the API Key / Secret in Postman, you'd put it in as "Basic Authentication". However, I don't recommend embedding API Keys in your mobile apps, as they can be easily intercepted, which would open your app to a bunch of holes.

If you're building a mobile app, I'd recommend reading the following:
https://stormpath.com/blog/tutorial-build-rest-api-mobile-apps-using-node-js
https://stormpath.com/blog/build-note-taking-app-swift-ios

**Comment by LamourBt** [comment]
But what about how to disable the /login / register /logout pages that stormpath provide by default

**Comment by edjiang** [comment]
See https://docs.stormpath.com/nodejs/express/latest/configuration.html#single-page-applications

You can disable our HTML views entirely, this is useful if you simply want to use our JSON API with your customized front-end application. Use this configuration to remove HTML from the content type list:

```Javascript
app.use(stormpath.init(app, {
  web: {
    produces: ['application/json']
  }
}));
```

**Comment by LamourBt** [comment]
@edjiang the pages (*login,register, logout) are still enabled what should I do ?

**Comment by edjiang** [comment]
Can you please post your config?

**Comment by LamourBt** [comment]
`
app.use(stormpath.init(app,{
     client:{
        apiKey: {
           id: "i remove these lines",
           secret:"i remove these lines"
        }
     },
     application: {
       href:" i remove these lines "
     },
     web: {
       produces:["application/json"]
     }
}));`

**Comment by edjiang** [comment]
That's weird. Mind jumping into our slack channel @ https://talkstormpath.shipit.xyz/ ? I can help you diagnose it there.
