### ISSUE TITLE
Config Object not being loadaed into  ValidateClientConfigStrategy.js

### ISSUE THREAD

**Issue by poxopox** [stormpath/express-stormpath#463]
Im getting this error when I updated the package to the latest version

`6 Jul 17:03:08 - Error: API key ID and secret is required.
    at newError (/home/lawrence/Development/sensorfact-web/node_modules/stormpath/node_modules/stormpath-config/lib/strategy/ValidateClientConfigStrategy.js:16:14)
    at ValidateClientConfigStrategy.process (/home/lawrence/Development/sensorfact-web/node_modules/stormpath/node_modules/stormpath-config/lib/strategy/ValidateClientConfigStrategy.js:34:12)
    at fn (/home/lawrence/Development/sensorfact-web/node_modules/async/lib/async.js:746:34)
    at /home/lawrence/Development/sensorfact-web/node_modules/async/lib/async.js:1213:16
    at /home/lawrence/Development/sensorfact-web/node_modules/async/lib/async.js:166:37
    at /home/lawrence/Development/sensorfact-web/node_modules/async/lib/async.js:706:43
    at /home/lawrence/Development/sensorfact-web/node_modules/async/lib/async.js:167:37
    at Immediate._onImmediate (/home/lawrence/Development/sensorfact-web/node_modules/async/lib/async.js:1206:34)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)`

**Comment by robertjd** [comment]
Can you tell us how you are providing your API Key and Secret to your application, e.g. through environment variables?  Thanks!

**Comment by poxopox** [comment]
I'm providing it through the parameters, `stormpath.init(app, stormpathOptions)` where the object is declared at the top of the server.js

**Comment by poxopox** [comment]
With some sleuthing, I found out that the client.on('ready') event is never fired.

**Comment by robertjd** [comment]
The ready event won't fire if there is an error while parsing the provided configuration, one error is when we can't find the API Keys.  Can you tell me which version of NPM you are using?  We've had some problems with 2.x doing something strange with the dependency tree, which affect our config loading order.

**Comment by poxopox** [comment]
My npm version is 3.8.6, Node is v5.12.0 and Im running on Ubuntu 14.04LTS if that matters.

**Comment by poxopox** [comment]
I found that the object containing the fields that throw the error in the ValidateClintConfig, go as far as the Client factory in clint.js:10, but the  ExtendConfigStrategy is returning undefined.

**Comment by typerandom** [comment]
Thanks! Could you also provide us with your `stormpathOptions` (with sensitive values omitted)? Just to have some insight on the configuration options that you are setting.

**Comment by mdeggies** [comment]
I tried with these two different settings and am getting the same error: 

```
var stormpathOptions = {
  'client' : {
    'apiKey' : {
      'id' : '5SUAQA5PF3O7HGH4URNS2ITGD',
      'secret' : '/CwZRUQWO+qnG51CPYyokiUECIn4A0bwMRZ7tTiXuKU'
    }
  },
  'application' : {
    'href' : 'https://api.stormpath.com/v1/applications/1ye3UQxhA6mcqmdcxclHge'
  }
}
```

```
var stormpathOptions = {
  'apiKey' : {
    'id' : '5SUAQA5PF3O7HGH4URNS2ITGD',
    'secret' : '/CwZRUQWO+qnG51CPYyokiUECIn4A0bwMRZ7tTiXuKU'
  },
  'application' : {
    'href' : 'https://api.stormpath.com/v1/applications/1ye3UQxhA6mcqmdcxclHge'
  }
}
```

**Comment by typerandom** [comment]
Unfortunately I don't really have a clear solution to this issue. In my case it was due to the `stormpath-node` version `0.0.13` being loaded. For some reason NPM was loading an old module. I manually removed the module directory and ran `$ npm install` and that fixed the issue. But with a clean install of the current version, I'm unable to replicate this.

@poxopox If you do `$ cat /home/lawrence/Development/sensorfact-web/node_modules/stormpath/node_modules/stormpath-config/package.json`, what version number do you see?

**Comment by poxopox** [comment]
`{
  "_args": [
    [
      "stormpath-config@0.0.22",
      "/home/lawrence/Development/sensorfact-web/node_modules/express-stormpath"
    ]
  ],
  "_from": "stormpath-config@0.0.22",
  "_id": "stormpath-config@0.0.22",
  "_inCache": true,
  "_installable": true,
  "_location": "/stormpath-config",
  "_nodeVersion": "0.12.0",
  "_npmOperationalInternal": {
    "host": "packages-12-west.internal.npmjs.com",
    "tmp": "tmp/stormpath-config-0.0.22.tgz_1456974275905_0.23874544515274465"
  },
  "_npmUser": {
    "email": "orhedenr@gmail.com",
    "name": "typerandom"
  },
  "_npmVersion": "3.3.4",
  "_phantomChildren": {},
  "_requested": {
    "name": "stormpath-config",
    "raw": "stormpath-config@0.0.22",
    "rawSpec": "0.0.22",
    "scope": null,
    "spec": "0.0.22",
    "type": "version"
  },
  "_requiredBy": [
    "/express-stormpath",
    "/stormpath"
  ],
  "_resolved": "https://registry.npmjs.org/stormpath-config/-/stormpath-config-0.0.22.tgz",
  "_shasum": "937af74f8583e85dee5cb437e5bae88cd43f68fe",
  "_shrinkwrap": null,
  "_spec": "stormpath-config@0.0.22",
  "_where": "/home/lawrence/Development/sensorfact-web/node_modules/express-stormpath",
  "author": {
    "name": "Stormpath, Inc."
  },
  "bugs": {
    "url": "https://github.com/stormpath/stormpath-node-config/issues"
  },
  "dependencies": {
    "async": "^1.4.2",
    "cloneextend": "0.0.3",
    "flat": "^2.0.0",
    "js-yaml": "^3.4.2",
    "lodash": "^4.0.0",
    "properties-parser": "^0.3.0"
  },
  "description": "Stormpath configuration loader.",
  "devDependencies": {
    "chai": "^3.4.0",
    "coveralls": "^2.11.4",
    "istanbul": "^0.4.0",
    "mocha": "^2.3.3",
    "mocha-lcov-reporter": "^1.0.0",
    "sinon": "^1.17.2",
    "stormpath": "^0.17.4",
    "temp": "^0.8.3"
  },
  "directories": {},
  "dist": {
    "shasum": "937af74f8583e85dee5cb437e5bae88cd43f68fe",
    "tarball": "https://registry.npmjs.org/stormpath-config/-/stormpath-config-0.0.22.tgz"
  },
  "gitHead": "f00a3b67a183458ae0159430c345a31caa8f5879",
  "homepage": "https://github.com/stormpath/stormpath-node-config",
  "keywords": [
    "express",
    "stormpath",
    "authentication",
    "security",
    "configuration"
  ],
  "license": "Apache-2.0",
  "main": "index.js",
  "maintainers": [
    {
      "email": "r@rdegges.com",
      "name": "rdegges"
    },
    {
      "email": "robert@robertjd.com",
      "name": "robertjd"
    },
    {
      "email": "orhedenr@gmail.com",
      "name": "typerandom"
    }
  ],
  "name": "stormpath-config",
  "optionalDependencies": {},
  "readme": "ERROR: No README data found!",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/stormpath/stormpath-node-config.git"
  },
  "scripts": {
    "test": "istanbul cover node_modules/mocha/bin/_mocha -- --check-leaks test --recursive",
    "test-travis": "istanbul cover node_modules/mocha/bin/_mocha --report lcovonly -- --reporter spec --recursive && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage"
  },
  "version": "0.0.22"
}
`
