### ISSUE TITLE
Bugs in setting environment variables

### ISSUE THREAD

**Issue by mdeggies** [stormpath/express-stormpath#467]
We offer a lot of different options to users to set their environment variables. There are three that don’t work: 

1) Setting the apiKey file path inline in the config to a .properties file. Example:

```
app.use(stormpath.init(app, {
  client: {
    apiKey: {
      file: '~/Desktop/apiKey.properties'
    }
  },
  application: {
    href: 'https://api.stormpath.com/v1/applications/1ye3UQxhA6mcqmdcxclHge'
  }
}));
```

The error thrown is ‘Error: API key ID and secret is required.’

NOTE: the same behavior is seen when client:{} is removed, and when the file path is full and does not include a ’~’.  

I threw in some console logs, and instead of going to LoadAPIKeyFromConfigStrategy.js (which handles the logic of loading API keys from a .properties file), _we're taken to LoadFileConfigStrategy.js (which handles the logic of loading API keys from ONLY .yml and .json files)._ 

2) Setting the API key ID and secret inline in the config. Example: 

```
app.use(stormpath.init(app, {
  client: {
    apiKey: {
      id: '5SUAQA5PF3O7HGH4URNS2ITGD',
      secret: '/CwZRUQWO+qnG51CPYyokiUECIn4A0bwMRZ7tTiXuKU'
    }
  },
  application: {
    href: 'https://api.stormpath.com/v1/applications/1ye3UQxhA6mcqmdcxclHge'
  }
}));
```

The error thrown is ‘Error: API key ID and secret is required.’

NOTE: the same behavior is seen when client:{} is removed.

In this case, we’re also taken to ‘LoadFileConfigStrategy.js’ — which does not have the logic to handle grabbing the id and secret from the config (as it only deals with loading API keys from .yml and .json files). 

3) Setting the apiKey file path inline in the config to a .yml or .json file. Example: 

```
app.use(stormpath.init(app, {
  client: {
    apiKey: {
      file: '~/Desktop/apiKey.yml'
    }
  },
  application: {
    href: 'https://api.stormpath.com/v1/applications/1ye3UQxhA6mcqmdcxclHge'
  }
}));
```

There's a couple issues with this. First, only .yml and .json files are accepted. It's a small issue, but .yaml should also be accepted and parsed the same way as .yml. This is a minor change. Second, we are correctly taken to 'LoadFileConfigStrategy.js' — but this does not correctly set the ID and secret, and the error thrown is ‘Error: API key ID and secret is required.’ 

NOTE: the same behavior is seen when client:{} is removed. Also, I tried all of the different possible combinations to set the environment variables in the .yml and .json files. For example, in the .yml file, I tried the following with no success: 

```
client: 
  apiKey: 
    id: '5SUAQA5PF3O7HGH4URNS2ITGD',
    secret: '/CwZRUQWO+qnG51CPYyokiUECIn4A0bwMRZ7tTiXuKU'
```

```
apiKey: 
  id: '5SUAQA5PF3O7HGH4URNS2ITGD',
  secret: '/CwZRUQWO+qnG51CPYyokiUECIn4A0bwMRZ7tTiXuKU'
```

```
id: '5SUAQA5PF3O7HGH4URNS2ITGD',
secret: '/CwZRUQWO+qnG51CPYyokiUECIn4A0bwMRZ7tTiXuKU'
```

I also tried setting the application href inside the .yml file to see if that would make any difference, and it did not. 

NPM version: 3.8.9, Node version: v6.2.0

**Comment by mdeggies** [comment]
Same behavior reported by a user with these configs: 
npm v 3.5.2 
node v 4.1.2

**Comment by typerandom** [comment]
Thanks for reporting this! I have fixed this issue in a new PR. But regarding YAML file extension, if `yaml` is something that people expect, then we need to add that as an alias. Also, you have an issue in your YAML file. The comma after the ID field is not allowed. See http://www.yamllint.com/.

**Comment by mdeggies** [comment]
Thanks robin! I think .yaml and .yml are expected.
