### ISSUE TITLE
Login form configuration not applied to HTML login form

### ISSUE THREAD

**Issue by mdeggies** [stormpath/express-stormpath#478]
Modifying the login fields in the app.init function shown in [the docs](https://docs.stormpath.com/nodejs/express/latest/login.html#form-customization) does not update the login view:

```
{
  web: {
    login: {
      form: {
        fields: {
          login: {
            label: 'Your Username or Password',
            placeholder: 'email@trustyapp.com'
          },
          password: {
            label: 'Your super-secure PAssw0rd!'
          }
        }
      }
    }
  }
}
```

I verified that the structure is right by comparing it against the config.yml file, available here: https://github.com/stormpath/express-stormpath/blob/master/lib/config.yml

PS: Modifying the registration form does work. The problem seems to just be with the login form.

**Comment by robertjd** [comment]
This is a problem for the HTML view, the JSON view is working correctly.
