### ISSUE TITLE
enterprise account

### ISSUE THREAD

**Issue by dtuyenle** [stormpath/express-stormpath#479]
If it were an enterprise account how to change the api.stormpath.com/sso ? It keeps redirect to api.stormpath.com/sso

**Comment by dtuyenle** [comment]
oh and btw worst nightware documentation.

**Comment by mdeggies** [comment]
Hey there -- You'll just need to configure the base URL to point to enterprise.stormpath.io instead of api.stormpath.com. You can do that in the stormpath init like this: 

```
app.use(stormpath.init(app, {
  baseUrl: 'https://enterprise.stormpath.io/v1'
}));
```

**Comment by dtuyenle** [comment]
baseUrl gave me error
error:  name=ResourceError, status=401, code=401, userMessage=Authentication required., developerMessage=Authentication with a valid API Key is required., moreInfo=http://www.stormpath.com/docs/quickstart/connect, message=HTTP 401, Stormpath 401 (http://www.stormpath.com/docs/quickstart/connect): Authentication with a valid API Key is required.

**Comment by mdeggies** [comment]
baseUrl should be spelled with an 'L'
Can you give that a try?

**Comment by mdeggies** [comment]
@dtuyenle Feel free to open this back up if you have any q's.
