### ISSUE TITLE
postLoginHandler should work with OAuth2 Password Grant(?)

### ISSUE THREAD

**Issue by passatgt** [stormpath/express-stormpath#507]
I'm not 100% sure, but i think postLoginHandler should run when a new access token is generated using /oauth/token, especially with grant_type=password, which is like a login function on mobile clients.

**Comment by robertjd** [comment]
Hi @passatgt , yes the `/oauth/token` endpoint should trigger the post-login handler if tokens are issued.  I confirmed that this isn't working and I'm going to open this as a bug.  Do you have a workaround in the meantime?  Let me know if I can help you find one, as that may be quicker (we're working on a few other issues this week and I'm not sure how quickly we can get to this one).  Thanks for the report!

**Comment by passatgt** [comment]
Currently i just setup another endpoint which is called by the app after successful login. I did not find a way to hook up a middleware to the oauth/token route after the token was returned, but if you have another idea, that would be great.
