### ISSUE TITLE
Custom idsite landing page

### ISSUE THREAD

**Issue by probal** [stormpath/express-stormpath#518]
Default landing page of idSite is / . Which eventually renders login page. But if I want my own custom landing page to idSite. That is :

```
web: {
    idSite: {
      enabled: true,
      loginUri: '/newsletter-login/',
      uri: '/idSiteResult'    // default setting
    },

```
What I expect is :  https://myhost.no/#/newsletter-login?jwt=eyJ0aWQiOi
What I get is : https://myhost.no/newsletter-login/#/?jwt=eyJ0aWQiOi 

Can anybody help me in this regard?

**Comment by robertjd** [comment]
Hello @probal , thank you for getting in touch.  The `loginUri` value should be the absolute path that you want the user to land on when they are sent to ID Site.  As such you will need to manually add the hash for this value, like this:

```
web: {
  idSite: {
    enabled: true,
    loginUri: '/#/newsletter-login/'
  }
}
```
Can you try that and let me know if it works?

**Comment by probal** [comment]
Thanks @robertjd . It works like charm.

**Comment by robertjd** [comment]
Great!  I'm glad I could help :)
