### ISSUE TITLE
SAML ID Site logout returns 400

### ISSUE THREAD

**Issue by mdeggies** [stormpath/express-stormpath#527]
Hey guys,

Using express-stormpath with ID Site enabled, I'm able to authenticate via SAML, but logging out returns a 400 error with message "Stormpath Account HREF (sub) in JWT not provided." Attached is the JWT response. I've tested this with OneLogin, Ping, and Okta, and get 400's when trying to logout every time. 

![screen shot 2016-09-20 at 11 43 09 am](https://cloud.githubusercontent.com/assets/12939567/18683985/6fcd4d00-7f27-11e6-9834-8aed8e7fdb29.png)

**Comment by mdeggies** [comment]
Couldn't test this in express without ID Site enabled because of https://github.com/stormpath/express-stormpath/issues/492

**Comment by mdeggies** [comment]
IAM issue

**Comment by robertjd** [comment]
This is a problem with the underlying `StormpathAssertionAuthenticator`: https://github.com/stormpath/stormpath-sdk-node/issues/547
