### ISSUE TITLE
/forgot and /change REST access?

### ISSUE THREAD

**Issue by subatomicglue** [stormpath/express-stormpath#543]
Looking at the docs: https://docs.stormpath.com/nodejs/express/latest/password_reset.html

There is no mention of resetting password using REST api only (without HTML page).

I currently have disabled HTML views with:
`produces: ['application/json']`

So, I am left wondering how to use lost password workflow...  Can I selectively enable HTML only on `/forgot` endpoint?  how?  setting `produces: ['application/json', 'text/html']` on `/forgot` didn't work.

**Comment by mdeggies** [comment]
Hey @subatomicglue, if you have 'produces: ['application/json'], no html pages will be rendered. What you'll want to do is manually trigger the password reset email using sendPasswordResetEmail(): https://docs.stormpath.com/nodejs/jsdoc/Application.html#sendPasswordResetEmail

**Comment by typerandom** [comment]
@subatomicglue 

The way you use the REST API to reset the password of an account is by doing a `POST` to the `/forgot` endpoint:

```
POST /forgot
Content-Type: application/json
Accept: application/json

{
  "email": "emailofaccounttoreset@example.com"
}
```

After this request, if the account exists then an email is sent with a link pointing back to your site. This link should contain a query string parameter named `sptoken`. Using this token, you can then do a `POST` the `/change` endpoint to change the password of your account:

```
POST /change
Content-Type: application/json
Accept: application/json

{
  "sptoken": "SPTOKEN_FROM_LINK_RECEIVED_IN_EMAIL"
  "password": "New account password."
}
```

I'm sorry for the lack of documentation, but I hope this helped you.

Cheers,

Robin

**Comment by typerandom** [comment]
I'm going to close this. Let me know if you have further questions and want this reopened.

**Comment by subatomicglue** [comment]
Excellent responses everyone, many thanks.  I'll dig into the REST API in the future when I don't see something in express-stormpath.  I didn't see it, but there isn't a basic javascript wrapper around the REST API is there?   All I see are specializations:  NodeJS, AngularJS, React, etc...   (I'm using Angular2 and it could be useful to have a basic Javascript access wrapper for your REST service, rather than having to write all the POST and GET myself...).

**Comment by robertjd** [comment]
Hi @subatomicglue , our REST API requires authentication with your tenant API Keys, and we don't permit this from the browser because it would be insecure.  We are working on a new "Client API" feature that exposes some common functionality for the browser, and we will be releasing that in our Angular and React SDKs in the next week.

**Comment by subatomicglue** [comment]
Nice, i'll look forward to that.   Any word on Angular2 support?

**Comment by mraible** [comment]
@subatomicglue We released a beta version of our Angular 2 support [a couple of weeks ago](https://stormpath.com/blog/angular-2-user-authentication). I updated it a couple days ago to contain support for [overriding component templates](https://www.npmjs.com/package/angular-stormpath#configuration).
