### ISSUE TITLE
https redirect on social login

### ISSUE THREAD

**Issue by merkelct** [stormpath/express-stormpath#545]
after deploying our new app out to test servers we are having issues getting the social login via google to redirect to https. Is there a way to configure this or override similar to 

```
social:{
      google:{
        scope: 'openid email profile'
      }
```

current code only redirects to http

**Comment by robertjd** [comment]
Hi @merkelct , can you tell me if you're using the `app.set('trust proxy', true)` configuration on your app?  This may be necessary if you are running behind a reverse proxy, such as the heroku environment.

**Comment by merkelct** [comment]
@robertjd we are not using that and we are behind an nginx proxy I will try that suggestion.

**Comment by robertjd** [comment]
Hi @merkelct , did that change work for you?
