### ISSUE TITLE
Cannot GET /logout

### ISSUE THREAD

**Issue by wjrivera** [stormpath/express-stormpath#548]
I can't seem to find in answer in the Issues section.
When i type my url (http://localhost:3300/logout), it does not reset my credentials.  I've read that the request had to be a post and made a form with post with a submit button and I'm still not able to get the credentials to reset, help?.  
Sorry for the formatting, I don't know why it shows up like that. 

************
`'use strict';

var express = require('express');
var stormpath = require('express-stormpath');
var path = require('path');
var app = express();

app.use('/', express.static(path.join(__dirname, 'public')));

app.use(stormpath.init(app, {
    application:{
        href: 'https://api.stormpath.com/v1/applications/1GlLaPsHyfIRTTLLCXKQvG'
    },
    web:{
        register:{
            enabled: false
        },
        logout:{
            enabled: true
        }
    }
}));

//Express Routing
app.get('/', stormpath.loginRequired, function (req, res) {
    res.send('Hi ' + req.user.givenName);
});

app.on('stormpath.ready',function(){
    console.log('Stormpath Ready');
    app.listen(3300);
});`
************

Node: v4.6.0
NPM: 3.10.8
Express: 4.14
Express-stormpath: 3.1.6

**Comment by edjiang** [comment]
You can use something like this snippet of code for log out:

```html
<a href="javascript:;" onclick="var f=document.createElement('form');f.method='POST';f.action='/logout';f.submit();">Logout</a>
```

or:

```html
<form method="post" id="logout">
    <input type="submit" name="logout" value="Logout">
</form>
```

**Comment by wjrivera** [comment]
With the first one:
Nothing happens
With the second one:
I get: Cannot POST
Thank you

**Comment by edjiang** [comment]
Oops, my second code snippet was wrong. Try this:

```html
<form method="post" action="/logout" id="logout">
    <input type="submit" name="logout" value="Logout">
</form>
```

**Comment by wjrivera** [comment]
It does the same thing as the first one, Nothing happens.

**Comment by edjiang** [comment]
What does "nothing" mean? Do you get redirected quickly and back? Does the button literally not click? Are you stuck in a redirect loop?

**Comment by wjrivera** [comment]
When i click on it, it does the Post, but stays on the same page.  If I refresh the page, the its wont redirect to login and exits the credentials

**Comment by edjiang** [comment]
Unfortunately, this is the most I can help debug within a public forum and the code that you've showed. I believe that there's something in your code that's conflicting, but it's hard for me to pin down without more info. Can you please email support@stormpath.com with more specific details of your application, and they can help you take a look? Thanks!

**Comment by wjrivera** [comment]
So from what you see so far in the javascript and html file, theoretically it should work?  I emailed them, thank you

**Comment by edjiang** [comment]
Yeah, you might want to try downloading the sample project, and see if you can get logout to work:

https://github.com/stormpath/express-stormpath-sample-project
