### ISSUE TITLE
Regression: LinkedIn login broken in 3.1.6

### ISSUE THREAD

**Issue by edjiang** [stormpath/express-stormpath#551]
Seems like we switched to using signed cookies in 3.1.6 for the OAuth State token, but are not decoding them as signed cookies. So the OAuth state doesn't match, and thus gets rejected with `Invalid state token provided`

Two questions:

1. Why'd we switch to signed cookies? I'm not sure if I see the benefit here.
2. We need to be decoding these cookies as signed cookies, or revert this change, as currently LinkedIn (and I'm guessing GitHub) login is broken with the `authorization_code` flow.

**Comment by robertjd** [comment]
Thanks @edjiang , we'll get this fixed.  No specific reason for the signed cookies, just something we decided to to.

**Comment by edjiang** [comment]
No problem =] Then should be an easy find/replace for `req.cookie` to `req.signedCookies` in some specific scenarios =]
