### ISSUE TITLE
'error:  Error: API key ID and secret is required.' even though I am setting environment variables.

### ISSUE THREAD

**Issue by dylanfpaul** [stormpath/express-stormpath#558]
I am on Ubuntu. And even though I export my STORMPATH_CLIENT_APIKEY_ID and STORMPATH_CLIENT_APIKEY_SECRET variables, it still is acting as if they don't exist. I even ran 'printenv' and I can see that they definitely do exist. Any help?

**Comment by edjiang** [comment]
It should be:

`STORMPATH_CLIENT_APIKEY_ID`

and

`STORMPATH_CLIENT_APIKEY_SECRET`

If there's a doc that misspells the environment variables, please give us a link so we can fix it!

Thanks!

**Comment by dylanfpaul** [comment]
Disregard the spelling in my first comment, I forgot to add the CLIENT part in my comment. But my variables are spelled correctly and it is still giving that error.

**Comment by robertjd** [comment]
Can you confirm that your environment variables are making it into the node process?  Before your call to `app.use(stormpath.init())`, add this to see what's available before we initialize stormpath:

```
console.log(process.env)
```

**Comment by dylanfpaul** [comment]
Okay, I did that, and my variables aren't showing up there. If I printenv just in my terminal at the root of the project, they do show up however. I don't know why this is.

**Comment by robertjd** [comment]
Some things to investigate:

* How are you starting the node process?  Is it starting in a new shell context?  If so, it won't share the same environment.
* Are you using any libraries that try to slurp in or auto-configure environment variables for you?  Sometimes those can modify the `process.env` value and cause issues.

**Comment by dylanfpaul** [comment]
I am guessing we are starting in a new shell context. How can I 'export STORMPATH_CLIENT_APIKEY_ID=***, etc.' in this new shell context it is using?

**Comment by robertjd** [comment]
That really depends on what your goals are for process management, which is outside the scope of help I can provide for this library.

If environment variables are tricky for your situation, you can also put a `stormpath.yaml` file in the root of your node project, and put the values in there:

```yaml
client:
  apiKey:
    id: YOUR_API_KEY_ID
    secret: YOUR_API_KEY_SECRET
```

**Comment by dylanfpaul** [comment]
Is that the exact syntax for the yaml file, or is that pseudo-code? I will try this.

**Comment by robertjd** [comment]
That should be correct, take a look at this example here: https://github.com/stormpath/express-stormpath-angular-sample-project#3-configuration

**Comment by dylanfpaul** [comment]
Hey, I got it to work by re-naming my stormpath.yaml file to stormpath.yml, it seems .yaml is not being picked up.

**Comment by robertjd** [comment]
Ah, my bad :) I'm glad it's working now!  If you're good with this approach, I'd like to close this issue.

**Comment by dylanfpaul** [comment]
Yes, you can close the issue. I think the source of my problem was that I was sort of handed this code base by another developer who is well versed in the configuration side of all of this. Me being exposed to this for the first time, it was hard for me to troubleshoot my issues. Thanks.
