### ISSUE TITLE
No default /login route

### ISSUE THREAD

**Issue by stevenmwade** [stormpath/express-stormpath#559]
The docs say:

> When you add Stormpath to your application using app.use(stormpath.init(app)), our module will automatically add the following routes to your application:

And inside the Login section it then says:

> If you want to make a login attempt from a front-end application (Angular, React), simply post a JSON body to the `/login` endpoint, with the following format:

I have the very simple application:

```javascript
let express = require('express');
let stormpath = require('express-stormpath');

let app = express();

app.use(stormpath.init(app, {
	web: {
	    produces: ['application/json']
	}
}));

app.listen(3000);

// Stormpath will let you know when it's ready to start authenticating users.
app.on('stormpath.ready', function () {
  console.log('Stormpath Ready!');
});
```

And when I make a post to the server I get this error:

`Cannot POST /login`

As far as I can see from the docs, there doesn't seem to be anything in my code that is incorrect.

**Comment by robertjd** [comment]
Hi @stevenmwade , thanks for reaching out!  Can you show us how you're making a POST to `/login`?  If the request prefers text/html, you'll get a 404 from this endpoint when it's configured to only produce json.

**Comment by stevenmwade** [comment]
@robertjd I am making the PAST with Postman and setting the content-type to `appplication/json`, but I can try with plain text.

**Comment by robertjd** [comment]
Can you look at the `Accept` header that postman is sending on the request?  The Accept header is the header that a client uses to tell the server which content type it wants the response to be in.  The Content-Type header is declaring the format of the data that is being sent to the server.

**Comment by stevenmwade** [comment]
```
Connection →keep-alive
Content-Length →19
Content-Type →text/html; charset=utf-8
Date →Wed, 14 Dec 2016 19:53:43 GMT
X-Content-Type-Options →nosniff
X-Powered-By →Express
```

**Comment by robertjd** [comment]
It looks like you need to add `Accept: application/json` to the request.

**Comment by stevenmwade** [comment]
@robertjd Nailed it. I'm surprised Postman isn't setting those itself. Thank you sir.

**Comment by robertjd** [comment]
No prob, happy to help!  I actually think we should handle this better on our side, we should infer the lack of an Accept header to mean you want the only configured response type.
