### ISSUE TITLE
Multi-Factor Authentication

### ISSUE THREAD

**Issue by wbobeirne** [stormpath/express-stormpath#561]
I don't see anything in the docs about 2FA, and I don't see any code similar to the one in the general node docs: https://docs.stormpath.com/rest/product-guide/latest/auth_n.html#using-multi-factor-authentication Is 2FA supported in express-stormpath at all? Or am I going to have to roll my own login implementation to make my server respect it?

**Comment by wbobeirne** [comment]
Ah, I see now there's a `mfa-support` branch, which tells me that this is still a work in progress. Feel free to close out this ticket if that is in fact the case.

**Comment by mdeggies** [comment]
Hey there -- We just finished drafting the MFA docs for the Node SDK and are working on the Express docs now in the mfa-support branch

**Comment by mdeggies** [comment]
Ah, yep! I'll go ahead and close this out, but feel free to take a look at that branch for more info. The MFA section of the Node docs are in the develop branch here: https://github.com/stormpath/stormpath-documentation/tree/develop

**Comment by robertjd** [comment]
Hi all, we don't yet have a default MFA experience in this express library, that is still several post-holiday weeks away.  If you need it in the meantime you will have to use the Node SDK to implement it manually in your Express application.  @mdeggies is working on creating some examples of how to do this, and those will go in our product guide.  

In the meantime, you can look at the API docs for the Node SDK to see how to work with the resources form there.  I would start here:

https://docs.stormpath.com/nodejs/jsdoc/Account.html#createFactor
