### ISSUE TITLE
postLoginHandler

### ISSUE THREAD

**Issue by Adam-Burke** [stormpath/express-stormpath#571]
Hi,

I'm enjoying using this library and stormpath in general. 

I'm trying to integrate firebase into express stormpath by creating custom firebase tokens and ideally passing them back to the user in the response of the oauth/token route. I'm using password grant token oauth2. It seems that the postLoginHandler hook is called after the response has already been returned to the user. Does that mean I'll need to request the firebase token in a seperate request? 

Thank you ,

Adam

**Comment by mdeggies** [comment]
Hey @Adam-Burke- the flow for both login and registration is pre-handler -> request to Stormpath -> post-handler. What exactly is the firebase token you're generating and what are you trying to do with it?
