### ISSUE TITLE
Node6 not supported

### ISSUE THREAD

**Issue by shikloshi** [stormpath/express-stormpath#575]
When upgrading to Node 6 (6.9.3) I get an error: 

```
eprecationWarning: crypto.pbkdf2 without specifying a digest is deprecated. Please specify a digest
```

Which is still not resolved in version `3.1.8`.

You must specify the digest algorithm (until now - sha1 was implicitly used if no algorithm was added to the function all).

**Comment by shikloshi** [comment]
Will add a pull request with the issue.

**Comment by Tweety-FER** [comment]
@shikloshi It's an issue in the Node SDK, and there's already a PR for that, it just hasn't been merged yet: https://github.com/stormpath/stormpath-sdk-node/pull/586

**Comment by shikloshi** [comment]
@Tweety-FER yeah, I figure it out a few minutes ago. thanks! will wait for it to merge.
