### ISSUE TITLE
400 error with okta-test-data.js

### ISSUE THREAD

**Issue by mdeggies** [stormpath/express-stormpath#616]
The script worked for me previously, and successfully created test data in Okta. Within the past 2 days, when running ``node ./node_modules/express-stormpath/util/okta-test-data.js --apiToken=$OKTA_APITOKEN --org=$OKTA_ORG``, I'm getting the following error:

```` 
ResourceError: HTTP 400, Okta E0000001 (E0000001): Api validation failed: actions.scopes. actions.scopes: Cannot add scopes to 'action.scopes', add to 'conditions.scopes.include' instead.
````

**Comment by robertjd** [comment]
This should now be fixed in RC4
