### ISSUE TITLE
Okta Group Expansion

### ISSUE THREAD

**Issue by mrosenberg** [stormpath/express-stormpath#620]
Thanks to the Stormpath for making this a relatively painless transition. Seems to be fairly easy so far. 

I have run into an issue where we use groups extensively in our app and use group expansion to retrieve those on authentication. Is there a similar option in the new Okta world. Group data doesn't seem to be included with the user object in 4-rc4. Do I need to make an additional request manually?

**Comment by robertjd** [comment]
Hi @mrosenberg , thanks for the notes!

This should be fixed in the new 4.0.0 release (official 4.x release), can you please try?  Have a great weekend!

**Comment by mrosenberg** [comment]
@robertjd Thanks. I'm hoping to test this out tomorrow.

**Comment by mrosenberg** [comment]
Groups are now included as expected. Thanks for fixing that up.
