### ISSUE TITLE
No reset email was received except Super Admin User

### ISSUE THREAD

**Issue by yang-cloudlet** [stormpath/express-stormpath#632]
Following the instruction from Change log and I have added the setting manually 

```
app.use(stormpath.init(app, {
  web: {
    changePassword: {
      enabled: true
    },
    forgotPassword: {
      enabled: true
    }
  }
}));
```

However, normal users are unable to receive any reset password email, the only one will receive is the Super Admin user. Am I missing anything in Okta Setting? 

Thank you

**Comment by mirko-lazarevic** [comment]
Same here

**Comment by rdegges** [comment]
This works for me when I test it out. Can you explain a little more what behavior you're seeing?

**Comment by yang-cloudlet** [comment]
@rdegges After retest it, It do receive the reset email, thank you.
