### ISSUE TITLE
Object <#Session> has no method reset() when logging out

### ISSUE THREAD

**Issue by PradatiusD** [stormpath/express-stormpath#9]
Currently testing the stormpath module and found that every time I would log out I would receive this `Object <#Session> has no method reset()`

I checked my `express-stormpath/lib/controllers.js` and found this.

``` js
module.exports.logout = function(req, res) {
  if (req.session) {
    req.session.reset();
  }

  res.redirect('/');
};
```

I switched `req.session.reset()` to `req.session.destroy()` to fix this temporarily but I wanted to know what the root cause was.  Let me know if there is any more info I can provide to help you.

Thanks!

**Comment by bobbycircle** [comment]
Excuse me, but how does one prevent one's instance of express-session from colliding with stormpath's? I think I'm having the same problem. Thanks for any advice!

**Comment by robertjd** [comment]
This part of the docs should help to explain let, let me know if you still have questions:

https://docs.stormpath.com/nodejs/express/product.html?highlight=session#session-management
